### ISSUE TITLE
Reload image files if source changed

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#278]
This probably only applies to a few controls that I an think of. The Kneeboard, the user image control, and probably the custom gauges. If the source has been modified Helios should reload the image.

**Comment by Todd1215** [comment]
commit a7919e8 fixed the image load issue but doesn't refresh the image if it changes.
if we use `BitmapCreateOptions.IgnoreImageCache;` that does fix the reloading of updated images but that may cause performance issues if we set that system wide because it ignores the cache.

**Comment by derammo** [comment]
This is definitely not something we should do across the board.  Not having bitmaps in memory is a non-starter.  Having notification to reload them from disk when changed still makes me very nervous, because controls can start failing in ways that can't be reproduced easily.   Like you suggest, maybe this makes sense for specific controls, but only as an option that has to be enabled.  

I see the use case for a kneeboard that allows you to load new images at run time.   

Can you explain why you would ever do this for the other controls you mentioned?

**Comment by Todd1215** [comment]
The only other control I can think of that has a legitimate usage would be the custom gauge. As an example of its use, a user is creating a F-16 CPD that has a moving map. The user wants the map to have all the steer points on it that comes out of BMS. An external tool already provides this map image that has the steer points on it. So the control will be loaded and needs to update the map file once the external tool generates it.

**Comment by derammo** [comment]
Ok no way that's a standard use of a user image.   It does seem neat to support as an option, even though performance is gonna get crushed.   How would the flow work?   Is there a notification when the image has been changed?   We don't want to load the image from disk 30 times a second...

**Comment by derammo** [comment]
(Unscheduled since we don't know what this is an it isn't committed.)

**Comment by Todd1215** [comment]
The third party tool that is currently used has its own notifications like popup messages. Could we possibly reload only when the kneeboard switch is incremented or decremented?

**Comment by Todd1215** [comment]
I have a working branch 'kneeboard-image-refresh' that allows kneeboard images to be refreshed when updated but other controls use the cache.

**Comment by Todd1215** [comment]
commit 1d93b1d5f01c006a8bebba441f29637b0b6afe57 fixes issue
