### ISSUE TITLE
Helios Files in Use - Installer Blocked by GIMP

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#280]
Installation of 1.6.3047 from Drive choked because I had an image open in GIMP.  The image was in %userprofile%\Documents\Helios\Images\Capt_Zeen\F18 (I'm presuming that the installer does not change any CZ images) so I am unclear why the installer detected this (I also thought that this install would be to "HeliosDev" and not "Helios" anyway.  So I'm presuming that the "file in use" checking in the installer is being over-zealous. The installation successfully "Try Again" continued after I closed GIMP.
![image](https://user-images.githubusercontent.com/18526232/88071713-19530880-cb6c-11ea-999e-4344e39de353.png)
Unless we are declaring that Helios\Images is for the exclusive use of Helios, then I think that the installer should be for specific sub-directories inside Helios\Images where we can reasonably expect to have exclusive control over the contents.

**Comment by derammo** [comment]
1) this is correctly "Helios" since it is not a build with a number like *.*.1???.*     Only builds 1000-1999 are development builds.  As a release candidate, 3047 is intended to replace Helios 1.4

2) Which of these three scenarios was this?

2a) you were installing over a 1.4 install (the error was part of uninstalling the 1.4)
2b) you were installing over a 1.6 install
2c) you were installing over nothing installed in "Helios"

I think I know what the bug is:  I put the Images folder in the installer as something to pre-create so it thinks it owns it.   Presumably, it is missing some flag that says "don't try to clean this up and you don't own files in it." 

But to make sure I do the right thing, please clarify which scenario this was.

**Comment by BlueFinBima** [comment]
OK, difficult to know, but potentially 2a) **and** 2b).  Is there a log from the installation?

**Comment by BlueFinBima** [comment]
1.6.3047 was in "Add Remove Programs" at >200MB in size.  Having reinstalled it, it is back to 59.8 MB.  Just documenting as another oddity.

**Comment by BlueFinBima** [comment]
Closing as unable to reproduce

**Comment by derammo** [comment]
I want to do some testing.  Everything you report is consistent with the following sequence (or similar):

1) empty documents\Helios folder
2) installer creates images folder
3) images copied in from profiles
4) due to incorrect flags, setup thinks image files are now owned by Helios install (the 200MB install size)
5) upgrade or uninstall wants to lock all those files

Something like that.  I still want to take a look at MSI flags we can set to make this better.   The only reason the installer pre-creates Images, Profiles, and Patches folders instead of waiting for Helios to do it is so that people can follow the instructions for a profile installation (which may mention those folders) even if they haven't run Helios yet.  That's why I put those folders back in the installer even though they are of course empty.  There was some feedback from testers before that it was better this way.  However, if it causes problems with ownership, I would rather back that back out and take them out of the folders.   

I assume there is one of the bit field attributes you can set on a directory entry in MSI that will say "you don't own this, just make sure it exists and leave it alone on uninstall."  I know the latter part exists at least.  I just need to wait a day or so until I have time to really test this.

**Comment by ertiyu** [comment]
an idea.
And if we remove the installation of the files but in return the user is invited to launch Helios just after the installation, the problem would be solved?

**Comment by derammo** [comment]
there aren't any attributes for directories (only files) and in any case none of this makes any sense.  An installer should never install anything into documents (not even directories) because if you have multiple user accounts, the component will appear broken (in need of repair) in any of those other accounts (because the documents files won't be there.)   

it's just garbage to install these folders directly.   In a future version, I will abandon writing anything outside program files and see if we can offer to run the profile editor or something like that.  Or maybe we just tell people they need to do that (so we don't end up with code in the installer.)

**Comment by derammo** [comment]
this works fine without having the documents folder precreated

**Comment by BlueFinBima** [comment]
Maybe this is a case where keeping the "just for me" install makes the use of %userprofie%\documents\Helios correct - at least some of the time.  I guess if it is installed for everyone, it should go into users\public\documents\Helios.  Should we consider moving at some point to %appdata%\HeliosVirtualCockpit\Helios?

**Comment by derammo** [comment]
no, we should not be writing anything to the user's files in an installer.  It makes zero sense.   If you push an application to a machine remotely, whose folders should it write?   Etc.   It is just a mistake in the original design that has now been corrected.

If a user does an interactive install, it should (just like every other piece of software :))  offer them to run the app at the end.   See #302 for a link to the MSI scripting we would need.   But the important bit is to leave the installer at that point and stop being root.   

I think for our uses, just telling people to run Profile Editor before unpacking their first CZ profile is perfectly fine.   It would be even more obvious once we have a "Profile | Install" feature where you can just point at a downloaded .rar file.  I didn't do it because I don't want RAR third party code right now.   In any case, once we do something like that, the issue is also moot.

**Comment by derammo** [comment]
installer is changed on rc1631
