### ISSUE TITLE
CALCULATION CONTROL

### ISSUE THREAD

**Issue by ertiyu** [HeliosVirtualCockpit/Helios#286]
A proposal.

A control accepting multiple inputs, and via a lua script will return a "triggerValue" which can interact with another control.
For example :
I position the control on my profile it is made up of 3 entries, a, b, c.
On a and b I enter via the input column a value resulting for example from the shared memory.
On c I enter via the Input column the position of another control present in the profile, for example a button.
In the control I write a Lua script:

if c == true then
return a + b
else
return a-b
end

In another control I use for example the result to display the calculated value.

With this new control no need to change the scope of variables in the program.

**Comment by derammo** [comment]
the issue with this design is that we don't know when a, b, and c are stable as a matching group.

Updates are delivered continuously in DCS, and there is nothing telling us which values "belong together".   So "a" could update first and then we would return a new value that maybe does not make any sense because that "a" does not go with the old "b".

so that would be a limitation.   I know BMS knows what values are matched pairs because of shared memory scanning.  but other interfaces don't.   so maybe we can have some optional "sync" pulse or something

**Comment by ertiyu** [comment]
is no longer relevant.
