### ISSUE TITLE
Error when resetting monitors

### ISSUE THREAD

**Issue by tarmonthir** [HeliosVirtualCockpit/Helios#294]
When importing CaptZeen's new A-10C profile into Helios 1.6, an error occurs that shows up in the profile editor problems log file.

[Helios_status_report_132405917015307759.txt](https://github.com/HeliosVirtualCockpit/Helios/files/5001681/Helios_status_report_132405917015307759.txt)
[Profile Editor Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/5001683/Profile.Editor.Problems.log)

**Comment by derammo** [comment]
confirmed real.   reproduced by using 16x10 aspect ratio screens and then resetting the A-10C_3.0 (non-b) profile by CZ

![image](https://user-images.githubusercontent.com/817160/88953862-83079c80-d267-11ea-91c3-e4dd72a4c43a.png)

the it crashes the same way

**Comment by derammo** [comment]
implementation detail: root cause is monitor key in monitor shadow tracking (monitor setup) is collapsing for two similar monitors, similar to previously encountered and fixed bug that causes monitors to consume each other's records because they are momentarily at the same coordinates during creation / deserialization / reset

**Comment by derammo** [comment]
confirmed root cause:  the key is having the monitor the same size and numbered backwards (left monitor is 2, right monitor is 1) which is opposite of profile.  While shuffling the monitors into the correct order, one monitor briefly becomes identical to the other.  This is a deep logic bug in monitor shadowing.

I am attaching a workaround for this specific profile.  I reversed the order of the monitors in the file and adjusted the bindings.  That way, it can be safely reset on a machine that has this monitor configuration.   

@tarmonthir can you please confirm this can be successfully reset on your setup?   I will start work on a real fix but it isn't immediate

[A10C_v3.0r.hpf.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5002939/A10C_v3.0r.hpf.zip)

**Comment by derammo** [comment]
PS: if this workaround doesn't work, you can swap your monitor cables to renumber the monitors so that 1 is on the left then you can use the existing profiles.  Weak sauce, I know.

**Comment by derammo** [comment]
internal:  this can be easily worked on by taking a profile that is reset for two monitors of any same size and then reversing them in the HPF.  on reset, they have to trade places and the clobbering will happen

**Comment by tarmonthir** [comment]
I can confirm that the workaround was successful.
