### ISSUE TITLE
DCS Additional Viewports my problem?

### ISSUE THREAD

**Issue by Zanzibare72** [HeliosVirtualCockpit/Helios#307]
In the photo I present my problem.
I don't know how to solve it.
I have probably done everything I found on your website.

![problem](https://user-images.githubusercontent.com/69328198/89589827-cacd8b80-d846-11ea-998e-9f0ebdb3167b.jpg)

**Comment by derammo** [comment]
Sorry it is a terrible message :).   I will improve the reporting of that sort of thing.

The issue here is that the file CDU_init did not look sufficiently like an unmodified DCS file, so Helios refuses to patch it.  It was already modified, which means you have other viewport mods installed.   Please remove the viewport mods (if you were using Capt Zeen's 1.4 version of the A-10C profile before, then this is the "Mods" files from "Monitor Configuration.")   

Remove these from your mod manager, since they are no longer used and interfere with Helios doing it better :).  

If you are not using a mod manager, then please run the DCS repair utility to reset all the files to their factory versions.  Then the patches will "fit."

![image](https://user-images.githubusercontent.com/817160/89647460-99c37a00-d88b-11ea-92a9-32b8000299b4.png)

That's what the message should have said.

**Comment by derammo** [comment]
Also: 

Do you have discord?   I hang out here all day helping people: https://discord.gg/qtvdVWc

**Comment by derammo** [comment]
#305

**Comment by derammo** [comment]
#293

**Comment by derammo** [comment]
user supported in Discord
