### ISSUE TITLE
control center fails to write preferences

### ISSUE THREAD

**Issue by cosmo238977** [HeliosVirtualCockpit/Helios#316]
[Helios_status_report_132420493287677069.txt](https://github.com/HeliosVirtualCockpit/Helios/files/5080541/Helios_status_report_132420493287677069.txt)
[Helios has written the report to the file 'Helios_status_report_132420493287677069.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by derammo** [comment]
probably the same as #290

internal:  assuming this is the same user who reported it on Discord with a screen shot showing an exception stack.   Exception was on DeleteFile from SaveSettings.  Thread looks like main.

internal: Waiting for confirmation if this is transient or repeatable.  If it does not happen again after reboot, it was likely some sort of hung lock on the preferences file.  Otherwise, this will marked as a duplicate.

**Comment by derammo** [comment]
@cosmo238977 you are not on the latest Helios https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.3104.0

probably unrelated, but why is your Preflight Check off?  did you have to hack up some of the files?

**Comment by cosmo238977** [comment]
Preflight check is just a switch in the drop down menu and I turned it off
cuz I don’t know what it for, I read the error from start to finish and
found that after installing Microsoft one drive and deleting avg some how
windows defender put all of Helios exe or msi files into a blocked status
so after turning that fetcher off Helios is working again so sorry for the
error reports if thy don’t help. But if I come across something weird I’ll
send it to you just in case it will help

**Comment by derammo** [comment]
FYI 
https://github.com/HeliosVirtualCockpit/Helios/wiki/Preflight-Check

yes switching Anti Virus means you lost your Anti Virus config and had to permit them all again.

duplicate #290
