### ISSUE TITLE
FC3 aircrafts are not work?

### ISSUE THREAD

**Issue by jiahao-shen** [HeliosVirtualCockpit/Helios#318]
The indicators on FC3 aircrafts are freeze, is it a bug?

**Comment by derammo** [comment]
please send the profile (*.hpf) you are trying to use. 

Just attach it here (without images folders!  :) )

**Comment by jiahao-shen** [comment]
I download it from offical website
[F-15C_v1.0_eng.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5081181/F-15C_v1.0_eng.zip)

**Comment by derammo** [comment]
ahh I see.  That's a profile from 1.4 that Capt Zeen has not made a Helios 1.6 version of.  I will take a look real quick.

He has this comment on his site "Soon i'll port the rest of the FC profiles.   Enjoy it!"
http://www.captzeen.com/helios/downloads.asp

**Comment by derammo** [comment]
ok two answers:

1) Looks like native Helios "Driver" support for FC3 is completely broken in 1.6.   

2) However, it can work using the Capt Zeen module for the profile.   I was able to fly with the attached version below.

I have adjusted the profile to use the Capt Zeen module for FC and also to add the MFCD

When he ports the rest of his profiles, I am sure he will do a much nicer job.

[F-15C_v1.0_eng.hpf.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5081266/F-15C_v1.0_eng.hpf.zip)

**Comment by ytdlder** [comment]
I haven't done alot on Github, so I don't know the etiquette: may I open this ticket?
Because I've been trying to no end to get the "display" instruments in FlamingCliffs 3 modules (specifically for now the F-15C) exported onto my LCDs.
The **VSD** works on it's own via the default "LEFT_MFCD", but the **TEWS** & **MPCD** don't.

Not even with CaptZeen's C-15C Helios profile... all other dials and such work (even though for some reason the numbers don't exactly match).

Is there ANY way to get those instruments displayed onto external displays?

Thanks!
