### ISSUE TITLE
Issue whit today open beta patch

### ISSUE THREAD

**Issue by shuyax80** [HeliosVirtualCockpit/Helios#323]
[Helios_status_report_132423368803143613.txt](https://github.com/HeliosVirtualCockpit/Helios/files/5098678/Helios_status_report_132423368803143613.txt)
[Helios has written the report to the file 'Helios_status_report_132423368803143613.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

if i try to apply the patches  i got that error 
![WhatsApp Image 2020-08-19 at 18 58 31](https://user-images.githubusercontent.com/66852198/90678118-8f778780-e25e-11ea-9761-dbb475c6547c.jpeg)

**Comment by Wild-Bill-Kelso** [comment]
Me as well. Same failure message.

**Comment by derammo** [comment]
i'm in the process of making the new patches

**Comment by derammo** [comment]
A hotfix is now available to adapt to OpenBeta build 53756.   No Helios upgrade is required.  The procedure for installing the hotfix is:

- In Profile Editor, select the DCS Additional Viewports interface (does not matter which profile)
- Click "Revert Patches" if that button is shown
- Exit Profile Editor
- Unpack the hotfix zip file, so that the included "Patches\..." folder becomes Documents\Helios\Patches\…
> WARNING: You must extract the entire zip and preserve the directory structure from the zip file exactly.  The top-level "Patches" folder goes into "Helios" and that's it.
- Start Profile Editor
- Select DCS Additional Viewports
- Click "Install Patches"
[Patching_Hotfix53756.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5099728/Patching_Hotfix53756.zip)

The hotfix zip file is attached.
