### ISSUE TITLE
Patch prob. with latest open beta

### ISSUE THREAD

**Issue by mnp555** [HeliosVirtualCockpit/Helios#332]
[Helios_status_report_132429642611502044.txt](https://github.com/HeliosVirtualCockpit/Helios/files/5133412/Helios_status_report_132429642611502044.txt)

**Comment by derammo** [comment]
@mnp555 do you have any Patches in "Documents\Helios\Patches" by any chance?

I am able to patch the latest OpenBeta (2.5.6.54046) with no problems and some of the other users have also confirmed it works.  So either you have patches present in the Helios documents folder (the current Helios always uses those, even if they are old #328) 

or otherwise you have some other mods installed that are modifying those files?

**Comment by derammo** [comment]
Actually, I can tell from the messages that it is running an old patch cluster.    Presumably this was found in your Documents\Helios\Patches and you need to remove those.

**Comment by derammo** [comment]
actually, much more likely explanation:   I just noticed you are on Steam.  You may still have a fake "autoupdate.cfg" and that would have an old version number in it so it is using the wrong patches.  That makes a lot of sense.

You were supposed to clean up the fake file as 1.6.3214 no longer requires it and it breaks patch versioning unless you update the file every time you update DCS.

https://github.com/HeliosVirtualCockpit/Helios/wiki/Change-Log#support-for-dcs-steam-edition-installations

**Comment by mnp555** [comment]
Hi,
I have Steam, I don't have not Patches in Documents\Helios\Patches, I do hve not the Patch directory in Documents\Helios. 
Cancelling fake  "autoupdate.cfg" and pointing to DCS.exe is possible run patches and everythings work like a charm (A10 and F18 Capt Zeen).
Thx you can close the issue as solved.
