### ISSUE TITLE
Helios 1.6 with dcs UFC app

### ISSUE THREAD

**Issue by riol396** [HeliosVirtualCockpit/Helios#338]
Hello,
I am a huge fan of Helios. I think it's great that the team behind it builds such awesome software for the DCS World community! I have a question, I am using Helios 1.6 and the Capt. Zeen profile for the F/A18C. It works fine for me but I am also trying to use the DCS UFC app (allows a tablet to control the UFC remotely). The app needs to run a script from the Export.lua, however Helios 1.6 overwrites the Export.lua . When I goto the advance options and set it so it is user defined (I forget the term specified) it still seems to overwrite the Export.lua, also, when I try the option to add the script it still will not work. I would appreciate any information on how I can run Helios 1.6 and the DCS UFC app together (or any custom scripts). If you need anymore information please just let me know, thank you for your time.

**Comment by derammo** [comment]
Hi.  What version of Helios is this?  With the current version, you should have all these options available:

https://github.com/HeliosVirtualCockpit/Helios/wiki/DCS-Interface#exportlua-generation
https://youtu.be/bkP-f7uWkO4

**Comment by derammo** [comment]
@riol396 notifications not working ? :)

**Comment by riol396** [comment]
Ty for getting back toe soo quickly. I was using the most recent 1.6 version when I had the issue. I uninstalled 1.6 and reinstalled 1.4 and the DCS UFC app worked fine with the older version. Im not savoy on programming so I am only guessing as to what is happening. So the DCS UFC app runs a script on the main Export.lua (scripts folder), in fact it is the only script in the lua. Im assuming that script directs it to another Export.lua that is in a subfolder used for the DCS UFC app. Since Helios 1.4 does not overwrite the Export.lua there is no interference with the script. However, Helios 1.6 uses the main  Export.lua so if I were to add the script to the main Export.lua (scripts folder) Helios 1.6 removes it because it doesn't meet the integrity check. When I add the DCS UFC app script to the Export16.lua in the Helios subfolder the app does not work. When I add the script using the Helios 1.6 add function, it also does not run the app. In the DCS UFC app install instructions it mentions it has to be the first script ran, so im not sure if that matters to Helios 1.6 or not. I really appreciate your time, again i am not versed with scripting just taking a wild guess here. If you need more info or screenshots I can probably get you some by the weekend. Thanks.

**Comment by derammo** [comment]
the reason I asked what version of Helios (exact version like 1.6.3214.0 or whatever) you are using is that none of this should be happening with current 1.6 (3214 or 3302.)   It was supposed to go like this:

a) you install the Export.lua from DCS UFC.   Helios recognizes the format of the Export.lua and you use the "Update file if possible" mode to just have it add its one line call to the end of the Export.lua file.

![image](https://user-images.githubusercontent.com/817160/91995617-08b6b600-ed06-11ea-8fa7-2a4e284f49ad.png)


or b) Helios can't understand the Export.lua from DCS UFC and you have to switch to "User will manage this file" because Helios doesn't know how to safely edit it.  Just switch to that mode and add the one line at the end that calls Helios' export script:

```
dofile(lfs.writedir().."Scripts\\Helios\\HeliosExport16.lua")
```
![image](https://user-images.githubusercontent.com/817160/91996004-7ebb1d00-ed06-11ea-9fb2-fcc7f72b87d8.png)

If you use option b) then you are basically telling Helios that you are doing it and to shut the heck up about it during Preflight Check  :).

**Comment by derammo** [comment]
to be more clear: you should always try option a) and when it tries to edit the file it will put up a dialog telling you if it can't do it.  At that point, you can switch to option b).

**Comment by derammo** [comment]
FYI: putting UFC exports first is necessary if the UFC export script does not correctly implement chaining (calling the scripts that are already registered before it.)  That's possible that they still have that problem, which will be fine because Helios puts itself last (and correctly implements chaining.)
