### ISSUE TITLE
IFEI Nozzle Position Needles for F/A-18C Hornet do not function

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#349]
@Denver29 Raised this in https://forums.eagle.ru/showpost.php?p=4500814&postcount=225

"The UEFI nozzle indicator needle don't move and is stuck to 0"

**Comment by BlueFinBima** [comment]
Reason for the nozzles not working is that the exports file is missing 4019 and 4020.  Can't spot at what point these disappeared.... maybe this only ever worked for me... that would be embarrassing.
Unfortunately the needles are behaving erratically which is certainly not what they had been doing.

**Comment by BlueFinBima** [comment]
@derammo you probably need to take a look at 
52d1d80 because I needed a mechanism to avoid arguments going into driver.arguments.

**Comment by derammo** [comment]
I just read it.   Why did you not just set format to null, which is the current mechanism for keeping something from being in the arguments array?

**Comment by derammo** [comment]
@BlueFinBima

**Comment by BlueFinBima** [comment]
@derammo I wanted to reduce the amount of code I was changing.  No functions today have a null passed in to their format arg, and while I could have changed the empty string to null for each GetDataElements(), I decided that a future AddFunction could add a blank format which we would not want that showing in the Exports so the additional test protected for this and killed two birds.

**Comment by derammo** [comment]
@BlueFinBima I think you misread the code.   All the functions that receive a value that should not be added to the arguments arrays in the export driver use null as the format.  This has always been the way it is.   Here are four examples in the original Gadroc code that do it explicitly, because a function is used that normally generates an exported argument:
https://github.com/HeliosVirtualCockpit/Helios/blob/f6769f857708c01cb70a26a66d159bce0fc111eb/Helios/Interfaces/DCS/A10C/A10CInterface.cs#L461 
https://github.com/HeliosVirtualCockpit/Helios/blob/f6769f857708c01cb70a26a66d159bce0fc111eb/Helios/Interfaces/DCS/BlackShark/BlackSharkInterface.cs#L334

In the post-Gadroc interfaces, this was apparently not understood and is just wrong in all the places.   Here is a find-in-solution search string I used to find most of them (regular expressions on):  ```AddFunction.*"2[0-9][0-9][0-9]```

Most of them are luckily bound to functions like "Text" that always construct their data element with a null format:  https://github.com/HeliosVirtualCockpit/Helios/blob/f6769f857708c01cb70a26a66d159bce0fc111eb/Helios/Interfaces/DCS/Common/Text.cs#L40

However, all the ones that use functions like "Axis" that can also be used with arguments are being called incorrectly (without setting their format to null.)

There are a ton of generated values in the newer interfaces though that we should fix.   Presumably DCS added some arguments in the 2000 range or simply started returning 0 for them and so our bugs were exposed?

**Comment by derammo** [comment]
careful though: there are over 2000 arguments in the F14, so those are not actually generated ones.  Obviously what I said above only applies to network values that are generated in ExportFunctions.lua

**Comment by BlueFinBima** [comment]
@derammo, Yes, my misunderstanding.  Fixed in the Hornet https://github.com/HeliosVirtualCockpit/Helios/commit/982a7ea39435ce8faf6f4d50f1b25966607c026e.  Having had a look at results of the find-in-solution, I don't think there are any others to be corrected. They all pass back null in one way or another.
