### ISSUE TITLE
FPS limiting from processInput()

### ISSUE THREAD

**Issue by charlestytler** [HeliosVirtualCockpit/Helios#373]
I've been seeing DCS frames per second get capped at a low FPS when running Helios. I did some testing, and to me it looks like some blocking functions in `helios_private.processInput()` (which has the socket receive calls) are the bottleneck.

For the test I used:
DCS:  `OpenBeta 2.5.6.57530`
Helios: `1.6.3308.0000`
Graphics Settings: Low and resolution to 1280x768 to avoid CPU/GPU bottlenecks unrelated to Helios.

The FPS measured was from the beginning of the `Instant Action->F/A-18C->Caucusus->Free Flight` mission without touching the controls.

Scenario | helios_impl.exportInterval | FPS
----------|-----------------------------|------
Empty export.lua file (No Helios connection) | N/A | 140-170
Helios export, Stopped Profile | 0.005 | 120-175
Helios export, Stopped Profile | 0.01 | 115-125
Helios export, Stopped Profile | 0.1 | 74-75
Helios export, Stopped Profile | 0.2 | 69-70
Helios export, Start Profile | 0.005 | 64-65
Helios export, Start Profile | 0.01 | 64-65
Helios export, Start Profile | 0.1 | 64-65
Helios export, Start Profile | 0.2 | 64-65
Start Profile, Comment out L119: `helios_private.processInput()` | 0.005 | 140-170
Start Profile, Comment out L119: `helios_private.processInput()` | 0.01 | 140-170
Start Profile, Comment out L119: `helios_private.processInput()` | 0.1 | 140-170
Start Profile, Comment out L119: `helios_private.processInput()` | 0.2 | 140-170

Some comments from the above:
- The Export Frequency (`helios_impl.exportInterval`) seems to actually start capping FPS when set below the game FPS
- It gets to a set FPS (64-65) when a profile is actually Started; while Starting and Stopping the profile I can watch the FPS drop to the bottleneck, then climb back up when stopped.
- I saw similar results at settings I normally play at (where nominal FPS is around 60fps, and Helios was capping it down to 40fps)

I would be interested if others can reproduce the same trends as my results.

**Comment by derammo** [comment]
what profile are you using for the test?  some of them have some rather awful feedback problems and inappropriate multiplexing of data

**Comment by derammo** [comment]
I agree by the way that the blocking read is garbage.  That function is original 1.4 stuff left over from Gadroc's 1.3 and I never changed it because I assumed there was a good reason it wasn't simply non blocking.  Since I don't observe any performance problems myself, it never bothered me.   But yeah you might change it to non blocking (in line 341) and see what you get

**Comment by charlestytler** [comment]
This was using the CaptZeen "F/A-18C V3.1 HELIOS PROFILE" I tested with, however I also made a pretty bare-bones F-18 profile using the default F-18 export driver (not the A-10C impersonating one), and see the same type of drop.

If I change `socket::settimeout(.001)` instead to `timeout(0)` it does significantly improve the drop.  

If I have nothing but Helios in the export script I'll get (unrelated to above graphic settings) 85fps nominally, then drops to 64fps when Starting my custom profile.
If I set timeout to 0, it instead drops from 85fps to 80fps.  

I set up two buttons with DCS commands and those still work with the timeout disabled. Not sure how robust it is, but I'll keep using it and see if any issues arise.

**Comment by derammo** [comment]
I ran the attached 4 profiles to test different amounts of exports, using a similar configuration and the same Helios (unmodified export script.)

I can't see any difference unfortunately.   I am curious if you do.


profile | initial fps | peak fps after flying straight |   |   |   |  
-- | -- | -- | -- | -- | -- | --
p1_empty_module | 125 | 145 |   |   |   | 1280x768
p2_lofunctions | 125 | 145 |   |   |   | 1camera
p3_driver | 121 | 145 |   |   |   | windowed
p4_cz_module | 121 | 145 |   |   |   | I9-9900K stock
  |   |   |   |   |   | RTX 2080 stock
  |   |   |   |   |   | F/A-18C instant action free flight
  |   |   |   |   |   | 2.5.6.55960
  |   |   |   |   |   | 1.6.3308.0

[Issue373_tests.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5546835/Issue373_tests.zip)

**Comment by derammo** [comment]
I am just curious now why you see such dramatic slow downs.   I agree we should fix the blocking socket.  I assume maybe it was just an error or there really was some reason a long time ago (maybe something wrong with luasocket in early DCS?).

The only reason I could see this change being a problem would be if luasocket has different discard behavior based on time out.  In other words, will it more aggressively drop sent datagrams if outgoing buffers are full?   It should not, but that would be one reason why someone would have put it in blocking mode just with an incredibly small time out.

DCS-BIOS uses non blocking I/O by the way, but they also have a more strict "shaping" in their sending code so they might not be at risk of buffer overruns anyway.   I don't know if Helios is.    I suspect testing this (even reviving my load testing rig for it) isn't worth the effort.

I'd be ok with including this change in the next release and then see if people complain.   We will roll out the next release (1.6.34xx) slowly anyway, since it has several medium risk things in it.

**Comment by derammo** [comment]
## IMPORTANT

Please make sure you aren't running DCS in debug logging mode.  We had a problem before where someone was told by ED support to put DCS in debug logging mode (autoexec.cfg) and then never put it back.   So DCS and Helios were both debug logging into dcs.log, destroying performance.

**Comment by charlestytler** [comment]
My DCS Log only has INFO and ERROR level information logged, I've attached one for reference.

I tried running all four profiles you sent, and see the same characteristic starts around 140fps, then drops to a steady 64fps when profile Starts. This is with a ryzen 5600x and rtx 3080. I can try investigating more next weekend with a previous PC, as I don't remember anything like this happening before, so thought it may have been due to some change in DCS or Helios.

[dcs.log](https://github.com/HeliosVirtualCockpit/Helios/files/5550543/dcs.log)

**Comment by derammo** [comment]
Ok cool.    Having worked with you before, I am confident we can figure this out.  Maybe next weekend we can take a recording with wireshark and look at exactly what happens when.    Technically tests p1 and p2 should have made your fps HIGHER once you start the profile, because it should be switching from a default driver or module (based on what you have lying around in your scripts folder) to an empty module that does nothing (in p1) or a FC-only driver (in p2.)   So even if you have no driver or mods, it would have switched from the default telemetry only driver (same as p2) to absolutely nothing in test p1.

**Comment by jcenzano** [comment]
HI there.
I was sent to this thread from Capt:Zeen discord, because I asked for help with this issue. I am seeing aldo DCS capped to 65FPS but with a little difference.

It happens no matter if Helios is runnig or not. Whenever this Helios line s present in the Export.lua file, the FPS drop is limited to 65, even when Helios itself is not running.

Besides the FPS being limited, the FPS in general are much lower and much less consistent than when the helios line is not present in the export.lua.

If you want I can detail the numbers, but I dont think that the actual numbers matter that much.

I am no developer or coder at all, but I just wanted you to know that there is someone else with the exact same problem and I wanted to offer my (very limited) help, just in case I can give you some info that you might need.

My specs:
i9-10900KF
RTX 3080 (latest drivers)
64GB RAM
Helios 1.6.3309.0000
Latest DCS open beta
Capt Zeen profile FA-18C_V3.0b
Resolution 7760x1440

I've checked several missions and issue happens in all of them. It also occurs in both fuill screen and windowed mode.

I hope you can fix this issue, because DCS experience is so much smoother when the issue is not happening. As I told you, it is not that much about the max FPS, but about the FPS inconsistency.

**Comment by charlestytler** [comment]
Hi @jcenzano thanks for posting, glad to get another data point, and assurance that I'm not alone at least. Do you have any other export functions included in your `export.lua`, and does the issue go away completely when all are disabled?

I believe I was seeing the FPS capping manifest in other scripts as well, but focused in on Helios alone for the tests above. When initially debugging I found some reports on the DCS forums of people having similar problems with the Winwing throttle scripts at some point.

@derammo I did some Wireshark inspecting when initially testing the exportInterval changes in my initial comment, and the published UDP messages appeared to all be coming out at the correct rate. So Helios exports themselves didn't appear to be getting throttled for the cases I checked, but I didn't save any of those logs. Do you have any other suggestions of places to inspect other than the port monitored by Helios?

**Comment by jcenzano** [comment]
Initially I had the Tacview entry in the export.lua and another one that I don't remember, but I commented them all out so the Helios entry is the only one now.

**Comment by derammo** [comment]
There are several things going on here, that are really separate issues.   Let's give them numbers:

1) blocking receivefrom:   it is probably silly that we still do this and we should just continue to test with non-blocking.  At least some of the slow downs reported are completely different with that change

2) the frequency of receivefrom:   On the sending side, we only incur the OS level call to send when we actually have something to send, based on the configured rates for high and low priority items and what values are changed.  However, on the receive side we try to receive (effectively poll) every frame no matter of activity.   This is sort of important, because if we poll at a lower rate, we will introduce delay in the processing of input.  Even a small delay would make rotary controls feel a lot less snappy, for example.  So I see very limited chances for improvement there.  We could probably cap it to 60Hz or something like that.  Worth studying if it still seems like the socket receive call is somehow causing a significant delay.    Probably need to do some instrumentation to see if it matters.

3) general bugs:   Maybe I wrote some nonsense when I had to change the "scheduling" a few months ago.  Something changed in  DCS and the old "NextEvent" based mechanism was causing performance issues.  So I switched it to a frame-based mechanism that does some simple throttling.  There is just no way that should lead to the inverse relationship that Charles reported.  It should definitely not be getting slower with a longer exportInterval, especially in tests where we don't actually generate much data to send.  That sounds like something is basically broken.  Of course that does not match with the reported observation that the rates of sending updates are correct.  I will need to measure and confirm and also code review. 

4) why I see no slow downs:   I have no idea.   I suspect I will have to write something to measure how long we actually spend on different parts, if the timer ticks we get from DCS are high enough resolution.   Then we could kick out average times over some reasonable span periodically to the log so we can actually quantify performance on your machines.

**Comment by jcenzano** [comment]
Wow, sorry, but what you just wrote sounds like freaking NASA language to me. Just let me know if there is something I can do at plain user lever.

I know this is not the forum for "user level" stuff and I do not want to introduce any further interacted noise in the discussion.

**Comment by derammo** [comment]
@jcenzano just being willing to test is all I can really ask for

**Comment by Wild-Bill-Kelso** [comment]
A few weeks ago I read you were asking for framerate drop instances. I did some testing and found the Helios app was eating 17fps when I started the overlay. I did multiple tests on Single Player Freeflight, ie., turning my head, looking at the headrest, turning on framerate, then switching on F-18 overlay. Frames went from 61 to 44. Staying as still as I could, stopped the overlay and frames went back up to 61. Combo of two screens is 7040x1440, system, Ryzen 9 3900x, 4.24ghz, 64gb-3600, 2080ti. No mention DCS debug mode in my autoexec.cfg.  Is there a DCS setting you can recommend as a solution? Thanks derammo,

**Comment by derammo** [comment]
@charlestytler how do you feel about the non blocking change?  have you been running with that a while now?  I am thinking of just putting that into the release that is imminent.

**Comment by derammo** [comment]
specifically, regarding this comment: 

> If I set timeout to 0, it instead drops from 85fps to 80fps.

I could see that being simply polling all those arguments and doing anything at all in the export Lua.  In fact, if you reported a drop from 85 to 80, I would say "yeah, we are doing something and it takes non-zero CPU time on DCS' main thread."  That's not a bug at that point.

**Comment by derammo** [comment]
scheduled for testing the partial implementation (just non blocking receive, no stats) for 34xx

**Comment by jcenzano** [comment]
hi derammo

i just wanted to give you some feedback. I installed 1634 and noe I have no FPS capping and no noticeable FPS reduction either.

thanks for fixing it!!
