### ISSUE TITLE
No A10C II Tank Killer Vehicle in Interface

### ISSUE THREAD

**Issue by AleixF** [HeliosVirtualCockpit/Helios#374]
Hi friends.

I'm trying to use CaptZeen A10C profile with A10C2. Viewports export is correct, but any of gauges do nothing. Looking the interface configuration A10CII doesn't appears at list.  

I can't find too a manual where to start to bind both cockpits. I plan to use only Tank Killer version, and send to graveyard the old A10C. 

There's anyone who can trow light over this?

**Comment by derammo** [comment]
The "official" A-10C II interface for Helios has not been released yet.   However, I previously created an A-10C II profile that you can use until more official stuff is available.

It does not include any A-10C II specific functionality (like the helmet control box) but instead is just the A-10C Capt Zeen profile hacked up to run correctly with A-10C II.

Install by unpacking the attached .zip file and double clicking the included .helios16 file to install.   You must have previously installed Capt Zeen's profile from http://captzeen.com/helios/downloads.asp  because my profile requires all the images from it.

(sorry for the extra unpacking step, github does not allow .helios16 files in comments)
[A10C2_hack_v2.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5556862/A10C2_hack_v2.zip)
