### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by ertiyu** [HeliosVirtualCockpit/Helios#381]
Good evening to you
I am using version 1.6.3423
I just noticed that there was a problem in the transmission of commands.
By clicking on a 3-way button I change the position of a rotary, which changes the value of a label.
When I click on the 3 votes button the ratative turns fine, but the values do not change in the label.
If I click directly on the ratative the values change in the label.

FYI I have a profile that has this provision created a few months ago that works fine. It's just with the new additions that this doesn't work.

A test profile.
[Test_Binding.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5721415/Test_Binding.zip)

**Comment by ertiyu** [comment]
Same thing with the kneeboard, the three-way only moves 2 pages.

[Desktop.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5724001/Desktop.zip)

**Comment by derammo** [comment]
behavior is correct.  The release notes for 1.6.34xx will clarify that the "Bypass Cascading Triggers" setting is now always set on by default.  This is because there are so many errors caused by people creating trigger loops and almost no problems caused by missing cascading triggers.

So these test profiles you made need to change that setting explicitly after creating the binding, since you expect the rotary to forward to event to the label:

![image](https://user-images.githubusercontent.com/817160/103045070-0eecce80-4551-11eb-825b-e34031542c97.png)

**Comment by ertiyu** [comment]
Thank you derammo. Sorry I didn't know about this option.
On the other hand for the KneeBoard and are three-way button, would it be possible to have the unchecked ticks by default?
This is the normal behavior we would expect from the kneeboard.
Thank you again for the time spent improving Helios.

**Comment by derammo** [comment]
I don't believe the bindings are correct for the knee board in your example.  I will reach out on Discord.

**Comment by derammo** [comment]
ok after review of the Kneeboard Switch and Kneeboard controls, I can't do anything about this.  These are really brittle and poorly designed.  In order to use the control, you have to make sure the binding from Kneeboard Switch to the Kneeboard  is allowing cascades.   In existing profiles, this would already be the case, since the default used to be to allow it.

I don't plan to do anything about it.
