### ISSUE TITLE
Xbox One

### ISSUE THREAD

**Issue by ertiyu** [HeliosVirtualCockpit/Helios#391]
Hello

I am posting here a problem that happens to a friend.
He wants to use an Xbox one controller to press buttons in Helios.
Its controller appears well in helios, it is functional in its interface.
But once the profile is launched, nothing happens.
We tested under Windows 10 it works by using "joystick".
We tested with a wathog no problem.
Not having a controller at home I ask you the question of what can come from this bizart behavior.
[test_button_warthog.zip](https://github.com/HeliosVirtualCockpit/Helios/files/5762020/test_button_warthog.zip)

**Comment by BlueFinBima** [comment]
@ertiyu My Xbox One controller appears as "Bluetooth XINPUT compatible input device" so I am assuming that your friend's is USB?  There is definitely something strange happening, because with my profile, it was working for a period in Control Center and then it stopped working.  It always works as expected in Profile Editor.  I'm back at work today, so limited ability to investigate further.

Can you please confirm that the XBox One controller is not unplugged (assuming that it is USB) between profile editor session and control center session,
Please  also confirm that Control Center is running on the same PC as Profile Editor.

**Comment by ertiyu** [comment]
Hello BlueFinBima.
 My best wishes for 2021
His Xboxe one is USB.
It is not unplugged between using the editor and the launcher.
Everything is on the same PC.
Yesterday I was with him via stream discord.
I just found a Switch controller in my house that is recognized as an Xbox360, no worries for me.

Thank you again for the time spent solving the problem.

**Comment by BlueFinBima** [comment]
@ertiyu Happy New Year to you as well.  I want to be cautious, and make sure that your friend's problem is the same as the one I am seeing.
My problem is recreated on Windows 10 Professional as follows:

1. Start the profile in Control Center (no DCS etc running).  **My XBox controller buttons show the indicators lighting in response to buttons pressed on the controller.**
2. I give another application focus.
3. Give focus back to Control Center - **Buttons no longer cause the indicators to respond**
4. Stop the profile
5. Start the XBox profile again - **Still nothing works**
6. Stop the Xbox profile
6. Start a different profile
7. Stop the different profile
8. Start the original XBox profile again  - **Everything works again**

I'd appreciate it if you could run through this test and let me know how much is the same and how much is different from my own experience.

**Comment by ertiyu** [comment]
Thank you
I see it with him as soon as possible

**Comment by BlueFinBima** [comment]
Quick google suggests that this is caused by XB1 driver issues and down-levelling the driver can fix the problem.  Old drivers can be found here http://www.catalog.update.microsoft.com/home.aspx
I am not in a position  to try this, and there may be other ways to fix the problem, however with the number of problem reports, I'm pretty sure that this is not a Helios problem.  Feel free to reopen if you find evidence that this might be a Helios problem.

**Comment by ertiyu** [comment]
Thank you BlueFinBima for the information. He doesn't want to change the driver, he's looking to find another "no name" controller.

**Comment by derammo** [comment]
I would try a PS4 controller

**Comment by ertiyu** [comment]
Thanks Ammo for the advice.
I just tested with a Switch controller, which is recognized by W10 as an xBox360, no problem.
