### ISSUE TITLE
Custom Tape - Add Auto-Load option to reload changed Tape Images without restarting Helios

### ISSUE THREAD

**Issue by linknetx** [HeliosVirtualCockpit/Helios#396]
Requesting that an Auto-Load option similar to the option in the Kneeboards Carousel be added to the Custom Tape.

This would then enable changed images loaded from applications such as Weapons Delivery Planner to be updated without having to completely restart the Helios Control Centre.

**Comment by derammo** [comment]
sounds cool, as long as it is disabled by default.  We don't want to break image caching for basically all the CZ profiles

**Comment by Todd1215** [comment]
Do to CustomTape what commit 19bc0d8 did for Kneeboards

**Comment by Todd1215** [comment]
After further review this seems like this would be better suited as a FalconGauge and not changing CustomTape to suit such a small need.

**Comment by Todd1215** [comment]
Reopen for reevaluation. Performing a refresh of the tape image based on a binding input is better suited and less invasive on the gauge. If you don't set the Reload tape binding then no reload of the tape image is performed, so it doesn't have impact unless you want to refresh the CustomTape gauge.

**Comment by Todd1215** [comment]
The binding method works ok and gets the job done of reloading the CustomTape image if it has changed since the last load. A side effect however is that if more than one CustomTape control is referencing the same file then all CustomTape controls will get the updated image regardless if they have the Tape refresh input binding set. I assume this is due to how ImageManager is managing the images so that image files are not duplicated across controls.
