### ISSUE TITLE
Wrong Monitor Resolution Calculation from Helios

### ISSUE THREAD

**Issue by MHSWAT** [HeliosVirtualCockpit/Helios#399]
I am not able to adjust the Helios profiles to my monitor resolution. 
Helios always converts my monitor resolution 2560x1440 + 1920x1080 ( = 2560+2520) down to 1707x960 + 1280x720 ( = 1707x1680).
This always displays my profile incorrectly between both monitors. 

Helios Profile Editor Monitor Setup Details

![image](https://user-images.githubusercontent.com/37730889/107117515-06d7bc80-687b-11eb-86e5-0834d572cbec.png)

I was able to find out with VS 2019 that there must be an error inside the `Helios/DisplayManager.cs` at line 153.

`Monitor heliosMonitor = new Monitor(ConvertPixels(deviceMode.dmPositionX),
                ConvertPixels(deviceMode.dmPositionY),
                ConvertPixels(deviceMode.dmPelsWidth),
                ConvertPixels(deviceMode.dmPelsHeight),
                deviceMode.dmDisplayOrientation);`

The variables `deviceMode.dmxxx` contain the correct resolutions of my monitors, but a conversion is done via the method `ConvertPixels()` (line 73), where the wrong values are written into the object. 

`public double ConvertPixels(int pixels)
        {
            return Math.Round(pixels * 96.0 / DPI);
        }`

I can't quite understand the reason for the conversion, since the values were already correct before.

Unfortunately, after the line is commented out, the profile editor does not apply the change. 
So I cannot test if it works without the conversion. 
I also have no idea if I am the only one with this problem and why it doesn't work (apparently only for me).

**Comment by derammo** [comment]
that's what happens if the scaling on your main display is set to 150% (hit windows start button, type "DPI")

https://github.com/HeliosVirtualCockpit/Helios/wiki/FAQ#can-i-use-screens-of-different-sizes

If that is the problem, then just set the sizing to 100%.

If you don't want to set the DPI or if your problem is something else, then just delete the "DCS Monitor Setup" interface from the profile and fix the monitor setup file yourself by hand.  That way, Helios will shut up about it and you can still use all other features.

**Comment by derammo** [comment]
Since you are looking at the code, I should mention that setting ANY screen to something other than 100% will cause this.  Helios is running as an "application that is aware of only one DPI setting, not one per monitor" in Windows, because the code to handle screens with different DPI was never written.

**Comment by MHSWAT** [comment]
Thanks for your quick reply and for the workaround. 
Strangely enough I had tested the same yesterday with 100% DPI and it didn't work.

I think the calculation of the DPI would have to be made afterwards and only for the monitor that was selected for the profile.
Otherwise the profile is displayed incorrectly, because Windows still works with the original resolution for the location of the views.
Therefore I think it is a bug, but with the workaround a not too big one.
