### ISSUE TITLE
Missing data in RWR under Falcon BMS

### ISSUE THREAD

**Issue by ertiyu** [HeliosVirtualCockpit/Helios#404]
On 4.35 the RWR present in the "Falcon Simulator" tab does not display all the contacts.
Here is a video.

https://youtu.be/XeNNS2gB8q0

**Comment by Todd1215** [comment]
is this just in 4.35 or does it also miss contacts in 4.34?

This Falcon specific gauge seems pointless now that you can get the RWR extracted straight from BMS as a texture. If I fix this all I'm going to do is rip out the code and replace it with the RWR texture for backwards compatibility with older profiles.

**Comment by ertiyu** [comment]
Indeed I did not use it before, but since the extractions do not work correctly in 4.35 it is very practical.

**Comment by Todd1215** [comment]
Can you use the BMS SharedMemoryRecorder by viper tools location [here](url)https://github.com/lightningviper/lightningstools/tree/master/releases/End%20User%20Applications/Falcon%20BMS%20Shared%20Memory%20Recorder/for%20Falcon%20BMS%204.34

Using the tool above record a session that duplicates that scenario you showed in the video and post the shared memory recording here so I can use it to troubleshoot

**Comment by ertiyu** [comment]
Here is a recording of the shared memory,
I also added two screenshots from the software that came with Falcon BMS.
One capture was made with version 4.35 and the other with version 4.34. Both give the same values.

![Data 4_35](https://user-images.githubusercontent.com/52707215/108532612-4f11c880-72d8-11eb-95aa-2ddaa497964e.png)
![Data 4_34](https://user-images.githubusercontent.com/52707215/108532620-520cb900-72d8-11eb-8e8e-2b20b152239b.png)

[save.zip](https://github.com/HeliosVirtualCockpit/Helios/files/6011431/save.zip)

**Comment by Todd1215** [comment]
There are several things wrong with the RWR gauge. The first is that due to BMS updates since the gauge was created (pre BMS version 4.32 I believe there have been RWR symbols added since then. The gauge only models the RWR in the block 50/52. Keeping this gauge up to date with BMS code is probably not what we want to be spending our time on. Helios already captures the RWR texture from BMS. So in my opinion no need to reinvent the wheel here. There are some other issues with this gauge that if it stays need to be fixed but I don't think it needs to hang around any longer.

**Comment by Todd1215** [comment]
I just checked the RadarSymbol enum against what is in lightningviper tools ThreatSymbols enum and they are the same, so unless lightningviper tools is missing symbols then we have a complete list.

**Comment by ertiyu** [comment]
MFDE understands all the symbols, see the screenshot
![MFDE 4_35](https://user-images.githubusercontent.com/52707215/108588642-950f7080-735a-11eb-9f7c-5d1afc44ae4f.png)
