### ISSUE TITLE
AV8B AFC swich not updating

### ISSUE THREAD

**Issue by lampie22** [HeliosVirtualCockpit/Helios#408]
AV8B AFC swich not updating in profile when changed in game. i checked the binding and it seems to be correct so maybe an interface issue?
![afc](https://user-images.githubusercontent.com/78164879/111868943-dc4a4a80-8974-11eb-9e50-89599202cf52.png)

**Comment by BlueFinBima** [comment]
@lampie22 Pretty sure this used to work, but I can reproduce the problem.  It has been a while since I flew the Harrier.  My version of the DCS aircraft has AFC reset as a fixed position and the forward position as momentary which seems a little odd.  Can you confirm that it has been this way round for a while?

**Comment by BlueFinBima** [comment]
So the AV-8B interface isn't correct for the way the aircraft currently works, but the aircraft isn't returning a consistent value when the cockpit switch is forward (it ranges from 0.7 to 1.0).  I've changed the interface to improve the operation, but it does not completely fix it.  If this has been caused by recent RAZBAM changes, then it might be worth waiting for a few weeks to see if the aircraft fixes itself.

**Comment by lampie22** [comment]
> @lampie22 Pretty sure this used to work, but I can reproduce the problem. It has been a while since I flew the Harrier. My version of the DCS aircraft has AFC reset as a fixed position and the forward position as momentary which seems a little odd. Can you confirm that it has been this way round for a while?

Yeah, so the way it should work, as i understand it, is the up position should hold if you successfully engage the AFC. If you are out of parameter or moving the stick when you try to engague the AFC it will act like a momentary (this is how I noticed the issue because I wanted a visual indicator to see if it the autopilot was engaged or not.) the aircraft will move the switch to the center position if you maneuver violently. The down position 'reset' should momentary though.

I'm not sure how long the bug has existen i only noticed it a few weeks ago after a long break from playing dcs but i didnt use the AFC swich with helios before that break.

**Comment by BlueFinBima** [comment]
Thanks, that operation makes sense.  The problematic bit for a Helios switch is that it is expecting a finite value for a switch position, and not a range of values.  I'll see what I can do to fix this.

**Comment by BlueFinBima** [comment]
@lampie22 I'm not sure when the next release of Helios is due to ship, but this fix should be included in it.

**Comment by lampie22** [comment]
> @lampie22 I'm not sure when the next release of Helios is due to ship, but this fix should be included in it.

amazing thank you!
