### ISSUE TITLE
Helios 1.6 - Unhandled Exception - Insufficient Memory to continue

### ISSUE THREAD

**Issue by Drichard1458** [HeliosVirtualCockpit/Helios#413]
I set up Helios 1.6 per instructions, for Falcon BMS 4.35U1, using Ice's latest 4.35U1profile.  

Everything works perfectly into any flight for about 1/2 hour of flying.  Immediately, the screen freezes and starts popping up a series of "Unhandled error in Presentation Core" windows, with  "Insufficient memory to continue the execution of the program".  It then shuts down both Helios and Falcon BMS, .

 - Newer computer with Intel I9 9900x, 32gb Ram 1tb SSD, and Nvidia RTX 2080TI (driver 27.21.14.6172)

Any help would be appreciated.
Thanks!

Dan

See attached **Control Center Problems log**.
[Control Center Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/6330002/Control.Center.Problems.log)

**Comment by Todd1215** [comment]
I'm sure the exception is not related to anything Helios is doing per say. I run the same Ice profile version 4.35-5 and the latest Helios without any of those memory issues your having. My system is memory wise is the same but GPU is less as well as CPU. So you shouldn't have any issue running BMS at this point with that profile. With that said I have a few questions for you @Drichard1458

1. What version of Helios did you install and was it 32bit version or 64 bit?
2. Is this the location where you copied the Ice profile and images to C:\Users\drich\Documents\Helios ?
3. Do you have a page file setup on that monster system and if so what is the page file size?
4. Without Helios running does BMS exhibit the same behavior after 1/2 hour?
5. can you run the Helios Ice profile without BMS running and does it exhibit the same behavior after 1/2 hour ?
6. Is there another profile for BMS that you can download and try to see if it's the profile causing the issue? If you don't have access to one I can provide a different profile for BMS  for you to try.

I'd really like to know how much memory is free on your system when this problem occurs as well as what the memory size is of the Control Center process. It would be great if you could try and capture that so we can reduce what might be the cause. I know the Ice profile can grow the Control Center process to 2+Gb in size due to all the charts and kneeboards, maps that it loads. 

You said your using the latest Ice 4.35U1 profile. So I'm assuming that is version 4.35-5 of the profile. If you're not running that one you may want to update yours to the latest 4.35-5 version. Since you just installed it I'm sure it's 4.35-5 but I have to ask as there were lots of changes to eliminate memory foot print.

**Comment by Todd1215** [comment]
Also please upload your bms configuration file for review

**Comment by derammo** [comment]
I wouldn't get all hung up on the "out of memory" error.   It could very easily be just an unhandled exception of another sort that ends up being interpreted as an out of memory error.  Just fix the cases where the exceptions are being thrown instead?

**Comment by derammo** [comment]
PS: the reason I am suspect of the bitmap buffers is because that is one of the few places where we allocate global heap memory that isn't being managed by the CLR.   Of course, if BMS really did leak and take up all real memory, then it could have the same effect.   So looking at the process sizes of BMS and Helios is the way to go I guess?

**Comment by Drichard1458** [comment]
Thanks for the quick reply!  
See answers below...

1. What version of Helios did you install and was it 32bit version or 64 bit? - **64 bit**
2. Is this the location where you copied the Ice profile and images to C:\Users\drich\Documents\Helios ? - **YES**
3. Do you have a page file setup on that monster system and if so what is the page file size? **49174MB**
4. Without Helios running does BMS exhibit the same behavior after 1/2 hour? - **NO**
5. Can you run the Helios Ice profile **(YES),** without BMS running and does it exhibit the same behavior after 1/2 hour ? - **NO**
6. Is there another profile for BMS that you can download and try to see if it's the profile causing the issue? If you don't have access to one I can provide a different profile for BMS for you to try. - **Can you send one to test?**
7. You said your using the latest Ice 4.35U1 profile. So I'm assuming that is version 4.35-5 of the profile. - **YES**
8. I'd really like to know how much memory is free on your system when this problem occurs as well as what the memory size is of the Control Center process. It would be great if you could try and capture that so we can reduce what might be the cause. - **What's the best way to do this?  (Nothing shows in the Control Center console)  In BMS, I get a flashing window in the upper right corner of BMS with memory status, that quickly disappears just before it shuts down.  If I can capture it, will that work, or would something else be better?**
9. **How do you fix a "leaking bitmap buffer"?**
10. Also please upload your bms configuration file for review...
[falcon bms cfg.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6330339/falcon.bms.cfg.txt)

Thanks!

**Comment by Drichard1458** [comment]
**Version 1.6.3504.0** !

**Comment by Todd1215** [comment]
Here's a profile you can try with bms. Don't worry about mapping the key file. We are more interested in just how the extractions behave and the control center size when the profile is running. Let us know if it exhibits the sane issue or not. 

https://github.com/Todd1215/wheelchocks-bms-viper/releases/tag/v1.0

**Comment by Drichard1458** [comment]
Everything ran **_smooth as silk_** for over an hour, with no glitches whatsoever!  (Awesome profile, by the way!)  
It's looking like I may have a bad or corrupted install of the Ice profile.
I'll remove the Ice profile and .key file and re-install them again, to see if that clears it up.
At least now I can zero in on possible future issues.
Thanks so very much!
You guys are magnificent!

**Comment by Todd1215** [comment]
Glad to hear. Possibly get with linknet on BMS forums for issues with his Ice profile.
