### ISSUE TITLE
This is not a bug...

### ISSUE THREAD

**Issue by karpiyon** [HeliosVirtualCockpit/Helios#423]
Hi,
I couldn't find a forum page so i decided to as here...
Ho can I export the MFD buttons **state** in for the **F16** in DCS?
Can I read this data in any way?
By **state** I mean the text adjacent to the MFD buttons which when presses will perform that action.
I need this for my voice attack plugin.

**Comment by Todd1215** [comment]
Please do not open an issue for none Helios related questions/bugs.. What your asking for is info related to DCS so you can make a VoiceAttack plugin. How about doing your own research, look up DCS-BIOS and see if that can get you what your after. I doubt it though because your asking for data that I'm not sure DCS even exports. The MFD viewports are graphical so no textual data is there to gather. If you have other questions please use the discord link for Helios https://discord.gg/6kKYCdAy for that kind of stuff.
