### ISSUE TITLE
Need "DCS Vehicles" options for F14A

### ISSUE THREAD

**Issue by PSYKO-nz** [HeliosVirtualCockpit/Helios#429]
there is no option for F14A in the vehicle options, can you please add one in so i can get my f14b pit to work with the f14a please

also while you are in the area probably could do one for the hind and it would be awesome if you could make a generic/basic option  so we can make basic setups for non-specific aircraft

love your work, helios has taken my pit build to a whole new level, would love an update to it, keep up the amazing work!

**Comment by derammo** [comment]
Each of these requests needs some more info / discussion.

1) There is no F14 interface built into Helios right now, so I am assuming you are using the F14B interface from Capt Zeen's profile, which uses a Capt Zeen module?  Like this?  

![image](https://user-images.githubusercontent.com/817160/125074663-916f5280-e08b-11eb-9a27-a001708f3ecd.png)

2) The Hind will likely be supported by another CZ module, since he is already working on one.    So we could presumably add it to the list in the module loader now after confirming what he will call it.   But again, this isn't just a Helios thing, we need requirements from Capt Zeen first.    Are you just suggesting we do that now?   Because we have no interface for that aircraft...

3) I don't know what you mean for a generic/base option.    We have two things in this area:   

3a) The generic interface, which has no actual DCS interface code in it (that's what Capt Zeen uses to write his own interface in Lua.)   It still needs to know what aircraft is going to be supported, so that it can switch profiles when you enter that aircraft.  The DCS interface for each aircraft is completely different, so there is no such thing as an interface that works for all aircraft, which the exceptions noted below in 3b.)

3b) The basic telemetry driver, which I added in 1.6 at some point.  This is a mode in the DCS interface which you can select in the "Module Format."   You would normally use that with the Generic interface.  If you do that, then this profile will tell the DCS export Lua code to just send the stuff that you can get from the Flaming Cliffs interface and that is not aircraft specific.  This includes things like air speed and altitude directly from DCS, without using the cockpit model of the aircraft at all.    This is like the information that is shown at the bottom of an F2 view or in the F10 view.   That won't match what the cockpit shows and it doesn't have any concept of gauges or switches.   That's really all you can export "for non-specific aircraft" and it only works if the server on which you are playing allows you to export this stuff (because hard core dog fight people might think this is cheating.)

**Comment by PSYKO-nz** [comment]
Hi again. Thank you for clearing that up for me please forgive my ignorance on the matter, I had mistakenly thought that the f14 would be like the a10 in that there is an a10a,c and c2 option for telling it what vehicle is being used, my mistake, again please for give my ignorance

**Comment by derammo** [comment]
You are correct that you will have to change things for the F-14A if its internal vehicle name in DCS is different from the F-14B. 

I see you have already replied to the thread that explains how to do this.  That would have been good information to reference to save me a bunch of time searching and trying to figure out what you want :)  .... ahem...
https://forums.eagle.ru/topic/254120-f-14-v20-helios-profile-capt-zeen-compatible-with-f-14a-135-gr/

The only piece missing in that solution is that you have to put a copy of the HeliosExport16.lua into your "My Documents\Helios\Scripts\Helios\..." folder, so that Helios will use your hacked up copy instead of the built in one.

Yes, it is a shitty work around, because that means you are now responsible for maintaining that file.  But we never built a proper solution to update Capt Zeen's module name maps.

**Comment by derammo** [comment]
dev notes: 

this item represents:

1) add F14A to module name map (see forum link above for working names)
2) add F14A to vehicle name list

**Comment by PSYKO-nz** [comment]
Sorry about not linking the file, I will make sure to do that in any future issues.

if I’m understanding you right the best course of action at this stage would be to do the hack and wait for an update?

I’ll ofcorse back up any files I change :)

**Comment by derammo** [comment]
> Sorry about not linking the file, I will make sure to do that in any future issues.
> 
> if I’m understanding you right the best course of action at this stage would be to do the hack and wait for an update?

yes

> what is the exact directory I need to copy the lua into?

My Documents\Helios\Scripts\Helios

> I’ll ofcorse back up any files I change :)

**Comment by PSYKO-nz** [comment]
just tried it, it all works with the hack, thanks for your help, ill update the forum post with the fix :) thanks again for all your help!!!
