### ISSUE TITLE
Improve failed patch installation reporting

### ISSUE THREAD

**Issue by Steve-Nam** [HeliosVirtualCockpit/Helios#432]
Dear Helios,

I've got error message after rearrange monitor with additional view port setting.
How could I resolve the issue?

[Helios_status_report_132711730157192167.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6841045/Helios_status_report_132711730157192167.txt)
[Helios has written the report to the file 'Helios_status_report_132711731964609169.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by derammo** [comment]
This isn't a bug, so please don't file an issue for it and just ask in the Discord server or just follow the FAQ.  This case is actually addressed in both the FAQ and the Get-Help page.
<https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help>

I am converting this issue to an enhancement request to improve the status report exporting, so that it isn't wasted.

Dev notes:

1) status report should not localize time stamp (see attached file)

2) error messages from failed patch installation should list the version of DCS and the version of the patch that was selected

**Comment by derammo** [comment]
it should now say something like 

![image](https://user-images.githubusercontent.com/817160/126692758-601fc474-365f-4565-8a23-5be20c3b031f.png)
