### ISSUE TITLE
F18-C Viewports patch issue.

### ISSUE THREAD

**Issue by riol396** [HeliosVirtualCockpit/Helios#437]
[Helios_status_report_132719860267565363.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6896846/Helios_status_report_132719860267565363.txt)
I have a fresh DCS (Steam) install but I am still getting the "moded viewports" error and can not run the Helios patch.

**Comment by derammo** [comment]
what exact version of DCS is that?   And is this Steam OpenBeta branch or Steam Release version?

**Comment by riol396** [comment]
Hello,

I have the latest DCS 2.7 Steam Release. I was doing some reading and I see that the Capt Zeen profiles may be whats causing the conflict? Also, is it better to run the Steam Open Beta? Thank you.

Get BlueMail for Android<https://bluemail.me>
On Jul 28, 2021, at 4:06 PM, derammo ***@***.******@***.***>> wrote:

what exact version of DCS is that? And is this Steam OpenBeta branch or Steam Release version?

**Comment by derammo** [comment]
Helios is more likely to work with the Release, so that's good.  

It is possible that you are in a bad state (files patched with the wrong version, some mods installed?)

Please run this in the game properties of your DCS Game on Steam Library:
![image](https://user-images.githubusercontent.com/817160/127427363-d714ad2c-d661-48eb-9aaf-209e97504f73.png)
 
That should let you fix any modified files.

Another possibility is that you have some extra patches that don't fit.   Please check your "My Documents\Helios\Patches" folder and make sure there isn't anything there.

**Comment by derammo** [comment]
Another case that would be easier to figure out once #432 ships in the next release.

**Comment by riol396** [comment]
I got it to work. The Steam version doesn't have the autoupdate.cfg file. So I used a zipped version provided on the discord chat. The version written on the autoupdate.cfg was the last DCS ver 2.5....., I just changed the text to the current version 2.7...., and the patches loaded. That must have been why I kept getting the patch error messages, because helios thought they were out of date.

Get BlueMail for Android<https://bluemail.me>
On Jul 28, 2021, at 8:35 PM, derammo ***@***.******@***.***>> wrote:

Another case that would be easier to figure out once #432<https://github.com/HeliosVirtualCockpit/Helios/issues/432> ships in the next release.

**Comment by derammo** [comment]
please just delete the autoupdate.cfg.   I was the one who provided the hack file when it was necessary, but it is not supposed to be used.   Helios will use the version stamped into dcs.exe when Steam is used, because there is no autoupdate.cfg. 

Please confirm it works without the file entirely to make sure there isn't some new bug.

I just updated the docs because this is still confusing people https://github.com/HeliosVirtualCockpit/Helios/wiki/DCS-Locations-to-Update#steam-support

**Comment by riol396** [comment]
Deleted the .cfg and used the EXE in the bin. Still working fine. Thanks for your support!

Get BlueMail for Android<https://bluemail.me>
On Jul 29, 2021, at 4:01 PM, derammo ***@***.******@***.***>> wrote:

please just delete the autoupdate.cfg. I was the one who provided the hack file when it was necessary, but it is not supposed to be used. Helios will use the version stamped into dcs.exe when Steam is used, because there is no autoupdate.cfg.

Please confirm it works without the file entirely to make sure there isn't some new bug.

I just updated the docs because this is still confusing people https://github.com/HeliosVirtualCockpit/Helios/wiki/DCS-Locations-to-Update#steam-support
