### ISSUE TITLE
cpt zeens profile not loading properly ?

### ISSUE THREAD

**Issue by cosmo238977** [HeliosVirtualCockpit/Helios#464]
[Helios has written the report to the file 'Helios_status_report_132778073110313106.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]
[Helios_status_report_132778073110313106.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7276388/Helios_status_report_132778073110313106.txt)

**Comment by BlueFinBima** [comment]
@cosmo238977 Can you please provide a description of what happens. What does "not loading properly" mean?  I can certainly see that your huey profile is missing a huge number of images.  Have you installed the profile correctly?  The images are supposed to be in the Capt_Zeen\huey\ directory.

**Comment by cosmo238977** [comment]
Screenshot (1).png   
hi thx for getting back to me iv installed the latest helios
 v1.6.5013.0.msi and have had capt zeen profiles on helios before 
but this time i installed the uh-1h_v3.0 capt zeen profile and i get this problem in the above screenshot shot 
i'm not very computer literate well not as much as to make my own profiles. i can't find a tutorial on how to find the right path to install the 
missing image files and fix the problem.
This has only happened with this profile iv installed f18 ka50 a10c a10c11 p51 in B format for my screen size and all have worked grate iv had a uh-1h veshion in the past that worked fine as well just not this copy 
hope iv provided enough information would love some help thx

**Comment by BlueFinBima** [comment]
It looks like Captain Zeen is not using the Helios 1.6 profile installer feature to install his profiles, so you need to extract the Helios directory (found one level down from UH-1H_V3.0 in the rar)  into %userprofile%\Documents\.  The result should be that the files from Capt Zeen's profile are in `%userprofile%\Documents\Helios\profiles` and the images directories are under   `%userprofile%\Documents\Helios\images.`

**From the Captain Zeen readme file:**

2- You can see how install Helios 1.6 in this [video](https://www.youtube.com/watch?v=N0gCVIRwzos)
3- You can see how install a profile using Helios profile editor in this [video](https://www.youtube.com/watch?v=IfS0AtndXAM)

It seems unlikely that your problem is with Helios, so if you need further assistance, I would encourage you to go to Captain Zeen's [Discord server](http://www.captzeen.com/helios/images/discord.jpg).

If you believe that this is actually a Helios problem, then this issue can be reopened.
