### ISSUE TITLE
Add Text Labels to Rockers

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#555]
It would be great if we could add a text label to rocker objects just like we can with button objects.

Placing labels over the switches works fine, but creates additional unnecessary objects and makes it impossible to select the rocker from the Monitor window. 

![Screenshot 2022-05-09 222445](https://user-images.githubusercontent.com/19675397/167536549-11458156-2e82-47a1-a1bc-06234d1165e4.jpg)

**Comment by BlueFinBima** [comment]
I fudged this with the inbuilt EUFD, and it does not look right when the rocker is moved because the label does not move.  A built-in label would also have the same issue, but obviously it would be easier for a profile to utilise.  Making the label no bigger than the text should mean that the top and bottom of the rocker can be pressed, but I agree that it is not ideal.
IMHO, the only answer which will look good is the label as part of the three images.
I'll add to the backlog.

**Comment by BlueFinBima** [comment]
Looking at the label code, if you don't have a background ticked, then the Hittest should return false and not obscure the underlying control.  If I have some time, I'll see if I can confirm this.

**Comment by BlueFinBima** [comment]
![image](https://user-images.githubusercontent.com/18526232/167695726-e201d1a0-42e4-4a01-99d3-0093e682528f.png)

**Comment by BlueFinBima** [comment]
https://github.com/HeliosVirtualCockpit/Helios/issues/556 now in Master.

**Comment by MedievalBunny** [comment]
Awesome! 

Is it just the one style, or do they all have labels?

**Comment by BlueFinBima** [comment]
Hi Alex, the existing Rockers are implemented as templates because they are actually ThreeWayToggles controls under the covers.  ThreeWayToggles don't really need a label, so I created a new Helios control called RockerSwitch.  There is only one of them, but you are free to change the underlying images as you see fit.  
![image](https://user-images.githubusercontent.com/18526232/167723869-a92c543c-02c5-41c8-9679-f608b735606f.png)

**Comment by BlueFinBima** [comment]
All base Rocker templates have now been updated to use the new RockerSwitch control giving them the ability to have text.
