### ISSUE TITLE
Gauge resized 

### ISSUE THREAD

**Issue by looping40** [HeliosVirtualCockpit/Helios#572]
Some gauges resize are broken when width/height ratio far from 1.
Child elements are not resized in the proper axis.
See F16/Airspeed, F16/FTIT, F18/LOX

It may be linked to the rotation passed when creating the GaugeNeedle
_needle = new GaugeNeedle("{Helios}/Gauges/F-16/Airspeed/asi_needle.xaml", new Point(182d, 188d), new Size(300d, 300d), new Point(150d, 150d), -90d);

**Comment by looping40** [comment]
In fact, the scale ratio width/heigh of the needle seems to be applied regardless the current rotation

**Comment by BlueFinBima** [comment]
@looping40 Sorry for overlooking this for so long.  The gauges in the toolbox are intended to remain 1:1 aspect ratio.  I think this issue is in the "Interesting observation" category, but I can't see the current operation of the gaugeNeedle as a bug.  If I'm missing why it would be desirable to have the needle scale differently as it rotates then let me know, otherwise I'll close as  correct behaviour.

**Comment by looping40** [comment]
Hello
I noticed this as I was displaying using some  small screens with a custom resolution. But to match the circulare mask opening I had over the screen, I had to change the x/y ratio. But then the needle look weird 🙄

**Comment by BlueFinBima** [comment]
Thanks for the explanation.  I guess it is not common to have a display which does not display at 1:1, but I understand the use case better.   This does sound like a display driver issue however, if Windows cannot render a square image on the display, I think this does not seem correct operation.
