### ISSUE TITLE
Toolbox AH-64D Gauges with ViewPorts  do not have the viewports positioned correctly

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#578]
![image](https://user-images.githubusercontent.com/18526232/177645348-f02e96d5-ef35-44b1-8744-c529c71da9a4.png)

**Comment by BlueFinBima** [comment]
This problem seems not to be a newly introduced issue, although probably only made common by how the AH-64 components use them.  It can be reproduced by placing the Viewport on a panel.  The Viewport position should be the sum of all the parent positions (this is my current thinking).

**Comment by derammo** [comment]
see #283 for history

probably dupe of #434

**Comment by derammo** [comment]
Read those related issues for context.  Like I said in 434, this is by design, since I felt it was too complicated to implement.   The shadow visuals mechanism is already plenty complicated and tracking every node in the ancestry while things are being added and removed from the scene is a lot.   I decided it wasn't worth it and we usually just put viewports at the root.

**Comment by derammo** [comment]
I didn't debug this code, but if it is just related to the fact that the shadow tree can't correctly track viewports inside your components, then it could also be possible to add an interface (under Capabilities) to such components (CompositeVisual that knows it has a Viewport child) that the shadow could recognize and chose to track especially, like it does monitors and viewports.   That is, if that's the problem.

**Comment by BlueFinBima** [comment]
Thanks for the additional thoughts.  Not sure that it is worth the time & effort.  I am ok with the fact that it isn't tracked... it can be updated by closing the Monitor Setup tab and reopening if it is a big issue for someone.  The main thing for me is that the model view is in either one of two positions (where it was or where it is) excepting the rotation case.  If the viewport model is somewhere completely different, then I think that is just confusing, and since there is a way to address the majority case, I think it is worth doing.

**Comment by derammo** [comment]
You could at least mark up the viewport shadow to know that it has a non-zero transform (i.e., has intermediate parents) so that the monitor setup could react to this fact and know stuff isn't going to be live.  Otherwise, you can create errors.   It will think things don't need to be re-generated when they do.

**Comment by BlueFinBima** [comment]
@derammo flag introduced in the shadow, and indication now appears in the Interface status.

**Comment by BlueFinBima** [comment]
Fixed (to some extent) in [1.6.5305.3](https://github.com/HeliosVirtualCockpit/Helios/releases/latest)
