### ISSUE TITLE
Viewports error

### ISSUE THREAD

**Issue by Terrytory001** [HeliosVirtualCockpit/Helios#580]
It is my first to use Helios, all other setting are fine to go, but only this viewports error happened, can help to have a look?
Thx.
[Helios_status_report_133020142476406514.txt](https://github.com/HeliosVirtualCockpit/Helios/files/9083734/Helios_status_report_133020142476406514.txt)

**Comment by BlueFinBima** [comment]
Hi @Terrytory001, 
typically the failure to apply a patch is due to the file being modified manually (or with another tool) prior to Helios attempting to patch the file.   In this case the file is `E:\DCS Open Beta\DCS World OpenBeta\Mods\aircraft\FA-18C\Cockpit\Scripts\fonts.lua`.
The file around line 130 should look like 
![image](https://user-images.githubusercontent.com/18526232/178287612-64e05524-c1f1-4a1f-ad02-43769f643fc1.png)

Please make sure you do not have viewport mods installed and run a DCS Repair (slow mode) to clean up DCS.

**Comment by BlueFinBima** [comment]
Hi @Terrytory001 If you're referring to 
```
"status": "DCS installation in 'E:\\DCS Open Beta\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\F14\\Cockpit\\Scripts\\HeadUpDisplay\\Indicator\\init.lua",
"status": "DCS installation in 'E:\\DCS Open Beta\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\F14\\Cockpit\\Scripts\\RWR\\Indicator\\Pilot\\init.lua",
"status": "DCS installation in 'E:\\DCS Open Beta\\DCS World OpenBeta' is missing some patches in Mods\\aircraft\\F14\\Cockpit\\Scripts\\RWR\\Indicator\\RIO\\init.lua",
```
Then I suspect that this will be https://github.com/HeliosVirtualCockpit/Helios/issues/579.  There will be a fixed set of patches in the next release of Helios although you're likely to need to manually revert the patch which is already applied to the files referenced above.

**Comment by BlueFinBima** [comment]
Closed due to inactivity
