### ISSUE TITLE
Unable to Install Update - Version Already Installed

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#593]
I'm getting an error when trying to install the 1.6.5305.2 update. The built-in version check from the Profile Editor gives me an update notification, but then when installing the update I get an error saying that version is already installed.
![Screenshot 2022-07-28 185333](https://user-images.githubusercontent.com/19675397/181656003-146e773d-c3e3-4b54-a059-ab194b1cd53f.jpg)
![Screenshot 2022-07-28 185344](https://user-images.githubusercontent.com/19675397/181656010-e6ac93c2-7c83-437d-ba4c-8a8e43c22c38.jpg)

**Comment by BlueFinBima** [comment]
@MedievalBunny Windows versioning and the Windows installer are a pain with 4 digit versioning, but this isn't anything new (unfortunately).  You have to uninstall the previous Helios before applying the new one.  We've had a few goes at trying to work around the limitations of the Windows Installer without success.

**Comment by MedievalBunny** [comment]
@BlueFinBima Huh, weird. I've not had a problem with previous patches.

**Comment by BlueFinBima** [comment]
@MedievalBunny Interesting, it has always been a problem for me, but possibly because I upgrade in much smaller increments than many people.  As I mentioned earlier, the problem is related to 4th digit, and looking at historical releases, it is not common for Helios to have releases where just the 4th digit (ie hotfix) has changed.

**Comment by BlueFinBima** [comment]
1.6.5306.4 will allow others to install without a reinstall.
