### ISSUE TITLE
Request DCS F-5E Tiger instrument and viewport

### ISSUE THREAD

**Issue by rglasinovic** [HeliosVirtualCockpit/Helios#595]
hi guys
Is it possible to have a instrument and viewport por F-5E Tiger II?
This app rocks!
Thanks.

**Comment by BlueFinBima** [comment]
Hi @rglasinovic, 
Nothing we'd like more than to expand the aircraft elements for DCS.  The Viewport(s) are relatively contained in terms of scope, but instruments are more complex and time consuming to produce for the Helios Toolbox however with a little ingenuity, many things can be accomplished in a Helios Profile without the need for changes to the Helios project.  

None of the active project members has a particular interest in the F-5E, and we are not provided with the modules for free.
Until someone with the skills, interest and F-5 module joins the project, this has to remain in the class of "nice idea".

**Comment by BlueFinBima** [comment]
@rglasinovic Do you know the files needed to be changed in the F-5E to make the viewports exportable (and also what needs to be changed).  If you do, then adding the patches for the viewports into Helios can be rolled into the next patch update.

**Comment by BlueFinBima** [comment]
F-5E Patches for the RWR and RADAR along with Viewport controls added to Helios.  Likely to go out in 1.6.603

**Comment by sobe1205** [comment]
For my Ikarus profile, in the monitor config file, I also have the following:
F_5E_UHF_PRESET = { x = 2892, y = 754, width = 115, height = 115 }

**Comment by BlueFinBima** [comment]
[932ea63](https://github.com/HeliosVirtualCockpit/Helios/commit/932ea6339b707c9940b569529f0d4867ece1e0c7)
@sobe1205 I had a look around the F-5E cockpit, but couldn't see anything which repeated the UHF Preset.  Seems a little excessive to waste a viewport on a UHF Preset repeater anyway IMHO (I realise that there is at least one precedent).  Unfortunately your comment was too late for 1.6.603 because it is a big piece of work to rebuild all the patches and generate a new viewport. 
If there is a very strong reason to have the UHF Preset repeated as a viewport, then I'll certainly consider for a future Helios release.

**Comment by sobe1205** [comment]
No problem.  I have attached the profile for the F5 in Ikarus.  Perhaps the repeater is not a viewport, but something else?
![F5 uhf repeater](https://github.com/HeliosVirtualCockpit/Helios/assets/15917034/5c0ccf24-300d-43c1-829d-bb829516b69e)

**Comment by sobe1205** [comment]
For future reference, here are the two Ikarus files for the F5.  Is it possible to use these files to help make the gauges in Helios?  BTW, no one has figured out where the art for the profile is located in Ikarus.  
[f5.zip](https://github.com/HeliosVirtualCockpit/Helios/files/12841239/f5.zip)

**Comment by BlueFinBima** [comment]
@sobe1205 Thanks, I saw that in the cockpit, but I assumed that was what would be repeated, rather than the repeater itself.  If that number isn't exposed as an argument, then I'm sure it can be found without resorting to a viewport. 
For reference, the patches and viewports are as far as I'm going.  I only have the F-15E on trial and there are other things higher up the priority list.

**Comment by BlueFinBima** [comment]
Patches for RADAR and RWR shipped in 1.6.6030.1 along with their viewport templates.

**Comment by BlueFinBima** [comment]
WIP, but most of the gauges are complete.

![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/1f5238ca-29b0-4a85-903e-ebc24623ff8b)
