### ISSUE TITLE
Unhandled Error in mscorlib

### ISSUE THREAD

**Issue by Busterheiman** [HeliosVirtualCockpit/Helios#659]
If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [x] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

**Describe the Helios Issue**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behavior**

**Screenshots**

**please complete the following information:**
 - Helios Version [eg 1.6.5100.1]
 - DCS Version [e.g. Open Beta 2.7.16.28111]
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Additional context**
Add any other context about the problem here.  (*this problem started happening when I ....*)

**Comment by Busterheiman** [comment]
![image](https://user-images.githubusercontent.com/106287965/204944729-5c623a86-0378-42f4-9683-c0466cc13fcb.png)

any help would be great

**Comment by gorkle** [comment]
Consider #485

**Comment by BlueFinBima** [comment]
@Busterheiman  "any help would be great".   I'll say the same to you. The template is there for a reason - it is there so we get some very basic information about the circumstances of the problem and try to help you using it. 
Crystal balls are expensive ;-)
@gorkle might be correct that this is a duplicate.  No way to tell without more information, but have a read of #485 and see if the discussion has any similarities with your situation.

**Comment by Todd1215** [comment]
@BlueFinBima considering that this is a common problem with the abundance of USB devices that have duplicate HID ID's etc, we should probably look in to trapping this error and informing the user that they already added an interface with the same ID.

**Comment by BlueFinBima** [comment]
@Todd1215 I sort of agree wrt to #485, but we don't actually know what **this** issue is because there is so little information.  While error handing can always be improved, I think we have a right to expect to uniquely identify a USB device so there must be a bug somewhere.  It has been a long time since I looked at the DirectX code, so once I get the next release out of the way, I'll circle back to #485.  
If it is linked with a discord post on CZ, then the user was adding the DCS Monitor Setup interface when the error happened... not sure I see the link with the DirectX problem screenshot above.

**Comment by BlueFinBima** [comment]
This seems to be #491 rather than the previously mentioned 485.

**Comment by BlueFinBima** [comment]
1.6.5700.0 shipped with extra protections and diagnostics in this area.  If the problem happens again, or you are aware that there are extra diagnostics produced, then please reopen this issue.
