### ISSUE TITLE
New Version HELIOS Fail viewport patching

### ISSUE THREAD

**Issue by Chonaa340** [HeliosVirtualCockpit/Helios#715]
[Helios has written the report to the file 'Helios_status_report_133208233056685458.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

I up dated to the new vewrsion of HELIOS and I get this message all the time...
![Helios Viewport patches installation FAIL](https://user-images.githubusercontent.com/101440426/218641538-058d5cca-78a1-41e2-a116-ea0981f36bc6.png)

**Comment by BlueFinBima** [comment]
This is likely because the file which is trying to be patched is not as it was shipped by DCS.  Please revert the patches and try to re-install the patches.  If this does not work, then run DCS repair to clean up the files (bin\dcs_updater.exe repair from the command line in the DCS installation folder) and then attempt to install the patches.

**Comment by Chonaa340** [comment]
Hi, and thanks for your fast answer.
I did a DCS clean and repair, and everything it’s working perfect now.
Many thanks for your help.

Regards
Ignacio

El 14 feb 2023, a las 9:22, BlueFinBima ***@***.***> escribió:

﻿

This is likely because the file which is trying to be patched is not as it was shipped by DCS. Please revert the patches and try to re-install the patches. If this does not work, then run DCS repair to clean up the files (bin\dcs_updater.exe repair from the command line in the DCS installation folder) and then attempt to install the patches.

**Comment by BlueFinBima** [comment]
You're welcome.  Glad the problem is resolved.
