### ISSUE TITLE
Unhandled Exception while adding new interface

### ISSUE THREAD

**Issue by Newguy1999** [HeliosVirtualCockpit/Helios#723]
![SharedScreenshot](https://user-images.githubusercontent.com/54189563/222926989-1b7020cb-f003-4f2b-9e89-cc6426360c9d.jpg)
Clicking "Add Interface" under profile pops up this screen, clicking OK sends me to an empty list of interfaces to add.

**Comment by BlueFinBima** [comment]
@Newguy1999 If this was a problem for everyone, then we'd know about it, so more information is needed (some of which would have been provided if you'd filled in the new issue template).  Things like "when did this problem start to happen, and what release of Helios are you running".  More specifically, have you started using a particular DirextX device?  You can try unplugging the DirectX devices to see if the problem is related to one of these.    

Please review #659 #491 #485 #677.

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)

**Describe the Helios Issue**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**please complete the following information:**
 - Helios Version [eg 1.6.5100.1]
 - DCS Version [e.g. Open Beta 2.7.16.28111]
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Additional context**
Add any other context about the problem here.  (*this problem started happening when I ....*)

**Comment by Todd1215** [comment]
The most likely cause is that you're adding a USB device that has a duplicate HID ID but like @BlueFinBima said you need to add some more details if you want assistance.

**Comment by Newguy1999** [comment]
@BlueFinBima I appologize for missing the template, when using the "new issue" link on [this help page](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help-with-Helios-Software) under step (1a) it sends you straight to a blank issue without the template, had I seen it I would have followed it. 

@Todd1215 your suggestion was correct as was the solution at #485, simply unplugging everything except a mouse solves the problem and process of elimination brought it down to an old foot pedal I don't use in DCS. 

Thank you both for the assistance.

**Comment by BlueFinBima** [comment]
@Newguy1999 Thanks for the feedback.  As Wheelchock says, this is likely related to a **duplicate** HID ID, so do you have two of these pedals, or are you using the same controller device for something else?  

Help page links changed to the issue template.
