### ISSUE TITLE
Helios & DCS The Way

### ISSUE THREAD

**Issue by ToastyBanK3nobi** [HeliosVirtualCockpit/Helios#733]
Hey @BlueFinBima,
i love your helios, it´s the best way to play the Game on three  monitors and one tablet (3 Mons for the Game; tablet with Spacedesk Sync for the MFD exports). Before the latest updates i also used your fork of DCS The Way to get it on my middle Monitor and it worked most of the time, unfortunately one of the last updates broke it totally for me. Since yesterday the way 2.0 came out with a lot of fixes i gave it a shot, and it´s kinda working, but i have to use scratchpad for the crosshair, because it´s only displaying it on the leftmost one - it does get the coords streight so no biggy, but it is anoying... Any plans on a new fork for the way by you?

Have a Good one!

![Bild_2023-04-18_133034537](https://user-images.githubusercontent.com/131154255/232763829-8896acb6-85ed-4570-9c71-a1987c2813f8.png)

**Comment by BlueFinBima** [comment]
@ToastyBanK3nobi I have no plans to update the fork of DCS The Way, and I have now archived that repo.

I also see that you're extremely new to Github.  For future reference, your question (wich is not really an issue) is about DCS The Way, so opening an issue against Helios is not appropriate.  For this reason I'm going to delete the issue because I cannot transfer this issue to a more appropriate location.
