### ISSUE TITLE
I find that Helios didnt put any code in it.So M2000C Radio Repeater still didnt work throught Helios. I need to set it up by myself?

### ISSUE THREAD

**Issue by Torattacker** [HeliosVirtualCockpit/Helios#745]
I find that Helios didnt put any code in it.So M2000C Radio Repeater still didnt work throught Helios. I need to set it up by myself?
i am using 1.6.6002
![1691070064862](https://github.com/HeliosVirtualCockpit/Helios/assets/111193971/9d74b945-57f7-44df-a615-7923334b9535)

**Comment by Torattacker** [comment]
![1691070189940](https://github.com/HeliosVirtualCockpit/Helios/assets/111193971/45e4d156-c93e-4037-b877-3d198db0a2ec)

**Comment by BlueFinBima** [comment]
The Radio Repeater control from the toolbox does auto bind - see attached capture.  I guess that the profile you're using might not have the bindings, but that is unlikely to be due to Helios.  In order to auto-bind, the correct interface needs to have been added before the item is dragged from the toolbox.  Helios will not autobind a control which has already been added to the  monitor. 
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/1aa45843-5ef0-47f5-ba5c-f2d44ede5181)
I am closing this as no problem found.

**Comment by Torattacker** [comment]
I have tried,but i still find the Radio Repeater control from the toolbox doesnt auto bind.
![c4d326feb841599a8efbcbf654ffcf5](https://github.com/HeliosVirtualCockpit/Helios/assets/111193971/9cd0d375-4f65-43b4-a0f9-908f791e9fd4)
![1c5b9c7429986aca6a7659ded5b2b02](https://github.com/HeliosVirtualCockpit/Helios/assets/111193971/bdc1986e-08fc-4a98-8a9f-58fd0f7ac927)
![b632776bf591726fa886f7174d6d040](https://github.com/HeliosVirtualCockpit/Helios/assets/111193971/03cb7090-bf8d-431e-a2ad-92b61eadd24c)

**Comment by Torattacker** [comment]
what happened?
