### ISSUE TITLE
Helios1.6.6061.1 cant send key commands to DCS.

### ISSUE THREAD

**Issue by Torattacker** [HeliosVirtualCockpit/Helios#806]
I just put a new button on my F14 helios panel.Now it didnt work in DCS after updating Helios1.6.6061.1.

**Comment by Torattacker** [comment]
![Uploading 1707361063655.jpg…]()

**Comment by Torattacker** [comment]
![1707361063655](https://github.com/HeliosVirtualCockpit/Helios/assets/111193971/a1499f7b-c604-464f-910b-3a167450c4ac)

**Comment by Torattacker** [comment]
![1707361237225](https://github.com/HeliosVirtualCockpit/Helios/assets/111193971/a35a0611-50ab-4d9a-b42d-3b72ae5973c0)

**Comment by BlueFinBima** [comment]
@Torattacker I'm closing this issue because it contains insufficient information about the problem, and you did not give the community much time to assist you before opening this issue on GitHub.  The Helios Bug Report "Get Started" is designed to maximise your chances of getting a resolution to your issue.  Please do not open a blank issue.

1.6.6061.0 **does** send keystrokes to DCS - I've just tried it and it works.
I suggest you work out when the last time the Keyboard interface worked for you, and then investigate any other software you installed which might be consuming the keystrokes intended for DCS.
The open source [Carnac](https://github.com/Code52/carnac/releases) package can help to diagnose keyboard issues, however it isn't especially clever at showing left and right versions of keys.
