### ISSUE TITLE
Request additional F-16 gauges and make them work with DCS

### ISSUE THREAD

**Issue by Todd1215** [HeliosVirtualCockpit/Helios#811]
An F-16 fuel gauge should be created to add to the list of available controls.

There are a few variations on the F-16 fuel gauge based on Blk. Obviously one that corresponds to the F-16 Blk 50 so DCS guys can use it. Possibly a few popular variants as well.

Fix the F-16 Fuel Flow gauge so it will accept other values besides PPH.

**Comment by BlueFinBima** [comment]
@Todd1215 Just finishing up work on the xaml version of the Block 50 Fuel Gauge.  One minor issue with the Totalizer "00" not rolling as in the DCS module, but at the moment, I'm not inclined to fix this.  There is a little work to do in order to adjust the DCS interface for the viper, so I'm thinking I'll just bundle this all up into a single commit to be delivered in 1.6.608 irrespective of whether there are other versions of the Fuel Gauge ready.   Thoughts?
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/18f6542e-0a8a-4ab2-8d35-7d2670149678)

**Comment by Todd1215** [comment]
The last two digits don't roll as the totalizer is to the nearest 100's of pounds. Other than that its a nice looking gauge. What value are you accepting in the input binding?

**Comment by BlueFinBima** [comment]
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/6a485d6a-f4c1-4ad3-bfaa-58ff784a6a7c)
Numeric is 0-1 with 1 representing 5000 for the needles and 100,000 for the Totalizer. 

The "issue" with the Total is that (at least in DCS), the last two digits are always "00" but the "00" rolls with the hundreds digit.

**Comment by Todd1215** [comment]
Since DCS only has a block 50, I don't see a purpose in creating more fuel gages

**Comment by BlueFinBima** [comment]
Fuel Flow gauge for the block 50 has been delivered in 1.6.608
