### ISSUE TITLE
unhandled error in system

### ISSUE THREAD

**Issue by maks2001-2007** [HeliosVirtualCockpit/Helios#813]
# HELP US TO HELP YOU

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [x ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue

after installation of Helios.1.6.6070.2 on DCS latest stable version 
and when opening helios control center or profile editor , receiving the same error warning

### Steps to Reproduce the problem
starting the applications 

### Expected behavior
unable to run both applications 

### Screenshots
![Screenshot 2024-03-01 145057](https://github.com/HeliosVirtualCockpit/Helios/assets/161848528/bcb9b396-37eb-4ad3-bfa0-d82039f16daa)

### Please complete the following information:
 - Helios Version 1.6.6070.2
 - DCS Version 2.9.3.51704
 

### The problem happened while using 

 - [x ] Profile Editor
 - [x ] Control Center
 

### Additional context
had deleted some one drive files on c: yesterday evening , before that helios worked like a charm 

2024-03-01 14:42:29.6694|ERROR|GadrocsWorkshop.Helios.Windows.ExceptionViewer|Unhandled exception occurred. Helios will exit.|System.UriFormatException
Ongeldige URI: de indeling van de URI kan niet worden bepaald.
   bij System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bij GadrocsWorkshop.Helios.ImageManager..ctor(String userImagePath)
   bij GadrocsWorkshop.Helios.HeliosInit.Initialize(String docPath, String logFileNameIgnored, LogLevel logLevel, HeliosApplication application)
   bij GadrocsWorkshop.Helios.ControlCenter.App.OnStartup(StartupEventArgs e)
   bij System.Windows.Application.<.ctor>b__1_0(Object unused)
   bij System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bij System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by BlueFinBima** [comment]
@maks2001-2007 There are two issues here:
1.  "Unable to run PE or CC."  I'm pretty sure you've got a corruption of image files (more likely the location of the image files) needed by Helios - likely due to the deletion you mentioned.  I don't see any reason to believe this is a Helios defect.  I suggest you unistall and re-install Helios.
2.  "Unhandled exception."  Helios should try to handle errors more gracefully.  I can only guess at where I think protection needs to be added (based on the limited information you have provided).  Before re-installing, can you please provide   
`%userprofile%\documents\Helios\Control Center.log`  `%userprofile%\documents\Helios\Control Center Problems.log`  `%userprofile%\documents\Helios\Profile Editor.log` `%userprofile%\documents\Helios\Profile Editor Problems.log` to see if these contain any more information about how to better handle the error.

**Comment by BlueFinBima** [comment]
## Note
Probably need to protect line 106 in ImageManager.cs  `_documentImageUri = new Uri(userImagePath);`

**Comment by BlueFinBima** [comment]
1. Stale
2. Delivered in 1.6.608
