### ISSUE TITLE
unhandled error in patching. 

### ISSUE THREAD

**Issue by Bigopus** [HeliosVirtualCockpit/Helios#815]
Whenever I load a profile in the profileditor, the error message ( in the comment) is on top and the editor closed.
Maybe it's my profil, but older profiles are not working too. my example profile is in the next comment, because in editing mode I can't it add here.

**Comment by Bigopus** [comment]
[Profile Editor.exe.2980.zip](https://github.com/HeliosVirtualCockpit/Helios/files/14638071/Profile.Editor.exe.2980.zip)

**Comment by Bigopus** [comment]
One of the profiles not working:
[A10CII_3M_V4_3.txt](https://github.com/HeliosVirtualCockpit/Helios/files/14638416/A10CII_3M_V4_3.txt)

**Comment by BlueFinBima** [comment]
@Bigopus Please close the issue you raised in Gadroc's repo, then provide the following information and include information from the unhandled exception, and the `Profile Editor.log` and `Profile Editor Problems.log`.  The Minidump might prove useful, but let's cover some of the basics first like explaining when the problem started happening, and precisely what you are doing before the exception happens.

---
# HELP US TO HELP YOU

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
*A clear and concise description of what the bug is, when it started to happen and any recent changes.*

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. *Go to '...'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

### Expected behavior
*A clear and concise description of what you expected to happen.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### Please complete the following information:
 - Helios Version [eg *1.6.5100.1*]
 - DCS Version [e.g. *Open Beta 2.7.16.28111*]
 - BMS Version

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context
*Add any other context about the problem here.  (eg this problem started happening when I ....)*

**Comment by BlueFinBima** [comment]
Closing as stale
