### ISSUE TITLE
Can F-18C IFEI be moved out of Viewports

### ISSUE THREAD

**Issue by rocketeer998** [HeliosVirtualCockpit/Helios#817]
Currently the DDIs, IFEI and RWR are found in F-18C Viewports, while all gauges are in F-18C Hornet group in Helios.

Only the DDIs appear to have a black background in VR which makes them readable. The gauges are floating over the extended display in VR, so are the IFEI and RWR. The IFEI fonts appear over this transparent background making it hard to read. The gauges at least have some faceplate, so partially readable.

Except for the left and right nozzle needle animation, the rest of IFEI data are all numbers which can be exported to a screen via DCS Bios. So is it possible to export these IFEI numbers in the Hornet group, not viewport, so that they become more readable in VR?

**Comment by rocketeer998** [comment]
![IMG_6335](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/03aa1616-6d04-4872-bc0a-d57b5f3ce0e3)

**Comment by rocketeer998** [comment]
I think the IFEI panel exists outside the viewport group. Several problems with this.

1. They are normally found under Input Tab, Interfaces. In this case, the IFEI exist under Monitor, not Interfaces
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/fa1d0bda-efb2-483f-ab06-ea57d79f9f1e)

2. The buttons like MODE, QTY etc have option to bind. I bound them. Nothing happens when I run the profile and DCS. Maybe because they should be under Interfaces and not Monitor. I bound gauges and UFC display lines for F15E under Interfaces and they work.
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/b61fa644-eb3d-439b-8826-fba002e1115b)

3. The non button fields, like RPM, Temp, Bingo, Fuel Flow etc. don't have option to bind them. I tried dragging them over, nothing happens.
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/4a4a8d25-311a-45f7-ada3-4ad0d3f0a107)
 
So buttons have options to bind but those don't work.
Non button display fields have no options to even bind so they don't work too.
This IFEI panel outside the viewport category seems to be meant for buttons and switches. They normally are. Occasionally there are scratchpad display there too which is nice. But right now no display field from IFEI panel seems to be available for binding.

**Comment by BlueFinBima** [comment]
@rocketeer998 I think your last update indicates that you are missing some of the basics about Helios operation.  Issues on this project are not intended for "How To" questions.  I suggest you review the [Getting Help section of the Wiki](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios) 

For a control (such as the IFEI) to react to a DCS module, it needs to be bound to an interface for the particular aircraft.  You don't have an aircraft interface in your profile.
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/83fd77c6-0b4d-456f-8c97-23868d8b82d4)
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/8b418b89-3a98-4ecb-a158-b0d65c3981bf)

This is what the IFEI control (as opposed to the viewport) looks like when it is bound correctly

https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/255eb306-fe68-492a-81ae-e29fbeb572d4

**Comment by rocketeer998** [comment]
first of all i thought this IFEI panel in the non viewport group was just for buttons. Good to see the displays are working too.

I did import the interface for F15E coz it had a special Helios download. Didn't realize to map for other aircrafts I have to do the same. Now I did that and got all the displays in the IFEI working.

Thanks for your help!

**Comment by rocketeer998** [comment]
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/5b3a05ef-501d-4eb5-af17-8037ae88e6cc)

the order on the left and right sides seem random. but I managed to bind all fields in the IFEI except this one which I have no idea what it is for and I don't find an equivalent name on the right side for binding.

**Comment by BlueFinBima** [comment]
You did a lot of work to bind the IFEI.  For this particular Helios gauge, that work wasn't necessary because it automatically binds to the FA-18C interface if it has been previously added to the profile.  See https://www.youtube.com/watch?v=lEhG-TtENWc
This issue has already been closed, and I am now removing my notifications for changes to this issue.  
For "How To" questions. I suggest you review the [Getting Help section of the Wiki](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios)

**Comment by rocketeer998** [comment]
The F-15E auto binds for me. But not the F-18C. That's why I manually did them. So now Helios auto binds for all aircrafts?

**Comment by rocketeer998** [comment]
It appears that I added the F18 interface after I already dragged the IFEI to the monitor. If I add the interface first then drag the IFEI to monitor the auto binding happens. Thanks for the info.
