### ISSUE TITLE
Unable to get correct screen resolution in dcs/f18c

### ISSUE THREAD

**Issue by SKYWARRIOR81** [HeliosVirtualCockpit/Helios#828]
i have a Coursair 48"screen set to 3440x1440 and am trying to match this to second screen 9 (number 2) 1920 x 1080. annoyingly the options menu does not accommodate this and whilst the modules all work the moving panels are correctly placed but the frame is half displayed on the right side of my main screen. i am not eloquent with P.C.as I normally use a Mac for general work and this set up for DCS sim. The monitor set up page when set to "Start at top left of my desktop" will not move the left hand green box frame to accommodate main monitor and no. 2. It maintains a border from monitor 3, therefore its being included in the calculations. I have studied a few videos and one says "Alter the Lua file to the required setting in DCS options Lua file". Will this fix my problem and if so where and how do i do it as I am frightened of .... it up !I  If can fix this  will have it all working it seems  as its all there but slightly in the wrong place. 
Thank you
![Screenshot 2024-06-15 220020](https://github.com/HeliosVirtualCockpit/Helios/assets/171926494/290f608a-b7f8-4eb8-9ce7-96b274353c87)

**Comment by BlueFinBima** [comment]
Hello @SKYWARRIOR81, the issues for this repo are primarily for verified bugs in the project.  Please refer to the [Get Help section of the WIKI](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios).
My personal recommendation would be to move the left hand screen (in Windows) so the top aligns with the other monitors and that you have set this in DCS options
![image](https://github.com/HeliosVirtualCockpit/Helios/assets/18526232/efcba145-1b55-4357-a011-d26ea8006338)
Hope this helps.
