### ISSUE TITLE
A10C2 SAI pitch angle W sign moves in opposite direction to the sim

### ISSUE THREAD

**Issue by rocketeer998** [HeliosVirtualCockpit/Helios#832]
In the A10CII SAI binding, there are only two options. Pitch adjust or pitch adjust needle, to bind to the pitch adjustment offset. When I turn the knob in the sim, it goes up, the W sign in the second monitor moves down, and vice versa. I tried both. Binding either one still makes it move in opposite direction in second monitor compared to the sim in main monitor.
![Capture](https://github.com/user-attachments/assets/09a19859-8f80-4341-85a5-312eb044c9aa)
![Capture2](https://github.com/user-attachments/assets/c215b88c-f4e3-4348-9a2c-1d6c9df26ac2)

**Comment by BlueFinBima** [comment]
The A-10C SAI gauge (ie the componets behind the glass) hark back to the original Helios 1.3 product and many profiles use this SAI in its current form.  Assuming it is actually necessary, changing this SAI adjustment would break user profiles which make use of the current behaviour.   If you need assistance getting the pitch adjustment bound, then I would recommend  following the Discord link in the Wiki section about [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help).  The Discord community has many knowledgable members who I am sure would be happy to assist you.
Hope this helps.

**Comment by MadKreator37** [comment]
Testing: 
SAI Pitch adjust knob( helios control and in-game) rotated clockwise moves the Wings downward instead of upward, rotated counter-clockwise moves the Wings upward.
- Range of movement (wings) does not correspond with full range of knob movements.
    - interface ( a-10c and c2) shows a value range on the SAI pitch adjust knob to be -1 to 1 ( verified in clickabledata.lua)
    - the Helios Toolbox SAI is expecting a range from 1 to 0 ( 1 being full downward deflection, 0 being full upward deflection)
- Created calibration filter to change the input values ( -1 to 1) to the expected output value (1 to 0) and Wings function correctly

- Recommended change- 
In the toolbox item: A-10C Warthog -> Backup ADI. Lower value, currently 1, should be changed to -1. Upper value, currently 0, should be changed to 1.
![Screenshot 2024-08-20 104040](https://github.com/user-attachments/assets/cc4dd189-8f1f-4f54-8ff8-28052f27716c)
![Screenshot 2024-08-20 104054](https://github.com/user-attachments/assets/a0882dea-e51d-4d11-b010-fe58a4a1494c)

**Comment by BlueFinBima** [comment]
@rocketeer998  A-10C SAI has been fixed which has required changing the A-10C and A-10C2 interfaces with the result that existing users will need to alter their bindings to the pitch adjustment of the SAI.  Artwork for the SAI tape and Wings have also been updated.  Shipped in 1.6.6100.4

**Comment by rocketeer998** [comment]
ok thanks for the fix!
