### ISSUE TITLE
A10C2 ADI no binding for adjust pitch trim

### ISSUE THREAD

**Issue by rocketeer998** [HeliosVirtualCockpit/Helios#833]
In the main ADI in A10CII, adjusting the pitch trim knob moves the artificial horizon up and down in the game, not the W sign. On the left in Helios, there is a pitch trim knob as input, but there is no equivalent in the bindings side on the right. 

Pitch and Pitch Steering bar offset have their matching binding. I can't find anything on the binding side to match to this pitch trim knob. 

In DCS Bios there a potentiometer to bind to, to adjust it. But I'm adjusting it with a mouse. that's the input part. The display part is done by Helios which should mirror the sim but it doesn't move when the horizon in the sim moves when pitch trim knob is adjusted with a mouse scroll.

![Capture3](https://github.com/user-attachments/assets/6bf3e49b-fdf9-4b0f-adaa-e2e59dee3eb5)
![Capture4](https://github.com/user-attachments/assets/2c1c25f6-6158-42d1-a3cc-d8279120bb5d)

**Comment by BlueFinBima** [comment]
The A-10C ADI gauge (ie the componets behind the glass) hark back to the original Helios 1.3 product.  The ADI gauge does not contain the external componenets to make adjustments, but obviously they can easily be added in your Helios profile.   If you'd filled in the [issue template](https://github.com/HeliosVirtualCockpit/Helios/issues/new/choose), there is a link which points to the Wiki section about [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help).  The link to Discord in the Wiki is probably the most appropriate route if you need assistance adding a control to allow your Helios profile to make the pitch adjustment.
Hope this helps.

**Comment by rocketeer998** [comment]
I don't understand. I thought you guys are the support team for Helios and only you have access to fix Helios stuff? how is the discord going to help? Isn't discord just users like me? unless they have come up with some work around?

U said the ADI gauge does not contain component to make adjustment but can easily be added to my profile. how does the profile fix this issue if it can't be binded in the interface?

I am not talking about the pitch trim knob, which can be controlled by dcs bios for that switch as a potentiometer. The visual display of the artificial horizon need to move up or down which is displayed by the viewport, which mostly work for everything else about the ADI except for adjust horizon up and down.

**Comment by BlueFinBima** [comment]
> only you have access to fix Helios stuff

Helios is open source, everyone has access to the source and can make any changes they desire.

> you guys are the support team

Helios is free software.  There is no "support team".  There are only a _very_ small number of people who contribute their time, skills and effort to the project (for free).

> how does the profile fix this issue

One option (which might have been suggested on Discord) is to take a look at Capt Zeen's A-10C profile and see how he got a working ADI.

I had a quick look at the A-10C ADI, and strangely the pitch offset wings are part of another image in the gauge, and  the pitch adjustment has never been implemented, which I agree should be rectified at some point. 

I've flagged this as a bug, so that if someone has the time and interest, they can pick this up and resolve it.

**Comment by rocketeer998** [comment]
ok thanks for the info. I thought some people or company owns Helios, like dcs bios. I'd ask Discord. Thanks!

**Comment by BlueFinBima** [comment]
@rocketeer998 I've now retagged this as **Behavior Is Correct**.  The Wings being part of the gauge image is correct because in the DCS A-10C module wings do not move.  There is no binding for the pitch adjust because DCS just sends a new pitch value when the in-game knob changes.  The pitch adjust in the interface is simply to move the knob in Helios / tell DCS that your in-game knob has changed position.
