### ISSUE TITLE
Patches not found

### ISSUE THREAD

**Issue by gurol7** [HeliosVirtualCockpit/Helios#850]
When I start helios, it recognizes the monitors 2140x1920 instead of 3840x2160 for all three, and when I try to add DCS Additional Viewports, system cant load the patches. I couldnt figure it out how Can I fix this problem. Thanks in advance.

**Comment by BlueFinBima** [comment]
Hi @gurol7, support for issues such as these is by the community on Discord.  Please see the section on [Get Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios) in the [Wiki](https://github.com/HeliosVirtualCockpit/Helios/wiki) for more details.
