### ISSUE TITLE
F16, CH47 key presses doubled on push and release. AH64 KU works fine

### ISSUE THREAD

**Issue by jenxism** [HeliosVirtualCockpit/Helios#855]
1. *Go to CH47 pilot CDU or F16 ICP
2. *Click on any keys on the CDU of F16 ICP
3. The keys take a double press. Its a press on the push in and release.  eg if I press the number 1 it will type 11 number 2 will type 22

 If i am using the AH64 KU it will work as you would expect 1 is 1 2 is 2 and no double inputs.

### Please complete the following information:
 - Helios Version [1.6.6111.1]
 - DCS Version [2.9.10.4160]
 - BMS Version

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

**Comment by BlueFinBima** [comment]
@jenxism I've checked the toolbox elements for CDU / KU for the CH-47F & AH-64D and both bind in an identical manner.  Typically this type of problem is caused by either duplicate bindings for the keys, or the sensitivity of the touch screen.  
![image](https://github.com/user-attachments/assets/d8f72f39-aa70-4d32-8472-a1e419f22eae)

Helios is  a community effort and there is much support available on Discord - please refer to the [Get Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help#7-if-you-need-help-because-you-cant-figure-out-how-to-do-something-in-helios) section of the wiki.
